/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.view;

import br.com.controller.CategoryController;
import br.com.dto.categoria.CategoryResponse;

import java.util.List;
import javax.swing.JButton;
import javax.swing.JTabbedPane;

/**
 *
 * @author gabrielnathan
 */
public class MainScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainScreen.class.getName());
    private final CategoryController categoryController;
    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        setLocationRelativeTo(null);
        this.categoryController = new CategoryController();
        loadCategories();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SwitchPanels = new javax.swing.JTabbedPane();
        InitialScreen = new javax.swing.JPanel();
        Logo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CrudButtons = new javax.swing.JPanel();
        btnCrudTasks = new javax.swing.JButton();
        btnCrudCategories = new javax.swing.JButton();
        btnCrudSessions = new javax.swing.JButton();
        TaskScreen = new javax.swing.JPanel();
        taskOptions = new javax.swing.JPanel();
        lblTask = new javax.swing.JLabel();
        boxTasks = new javax.swing.JComboBox<>();
        btnStartTask = new javax.swing.JButton();
        lblDuration = new javax.swing.JLabel();
        txtTaskDuration = new javax.swing.JTextField();
        lblTimer = new javax.swing.JLabel();
        progressDuration = new javax.swing.JProgressBar();
        txtStatus = new javax.swing.JLabel();
        btnReturnInitialTask = new javax.swing.JButton();
        btnReturnInitialTask1 = new javax.swing.JButton();
        btnReturnInitialTask2 = new javax.swing.JButton();
        btnReturnInitialTask3 = new javax.swing.JButton();
        taskContent = new javax.swing.JPanel();
        taskScrollPane = new javax.swing.JScrollPane();
        taskTable = new javax.swing.JTable();
        CategoryScreen = new javax.swing.JPanel();
        categoryOptions = new javax.swing.JPanel();
        btnCreateTask1 = new javax.swing.JButton();
        btnUpdateTask1 = new javax.swing.JButton();
        btnDeleteTask1 = new javax.swing.JButton();
        btnReturnInitialTask5 = new javax.swing.JButton();
        btnReturnInitialTask7 = new javax.swing.JButton();
        categoryContent = new javax.swing.JPanel();
        categoryScrollPane = new javax.swing.JScrollPane();
        categoryTable = new javax.swing.JTable();
        SessionScreen = new javax.swing.JPanel();
        sessionOptions = new javax.swing.JPanel();
        sessionContent = new javax.swing.JPanel();
        sessionScrollPane = new javax.swing.JScrollPane();
        sessionTable = new javax.swing.JTable();
        taskRegisterPanel = new javax.swing.JPanel();
        categoryRegisterPanel = new javax.swing.JPanel();
        sessionRegisterPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setName("MainFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SwitchPanels.setMaximumSize(new java.awt.Dimension(800, 400));
        SwitchPanels.setMinimumSize(new java.awt.Dimension(800, 400));
        SwitchPanels.setPreferredSize(new java.awt.Dimension(800, 400));

        InitialScreen.setPreferredSize(new java.awt.Dimension(600, 400));

        Logo.setPreferredSize(new java.awt.Dimension(600, 150));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setText("Pomodoro");
        jLabel3.setAlignmentY(0.0F);

        javax.swing.GroupLayout LogoLayout = new javax.swing.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(255, 255, 255))
        );
        LogoLayout.setVerticalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(44, 44, 44))
        );

        CrudButtons.setPreferredSize(new java.awt.Dimension(600, 250));

        btnCrudTasks.setText("Tarefas");
        btnCrudTasks.setMaximumSize(new java.awt.Dimension(50, 50));
        btnCrudTasks.setMinimumSize(new java.awt.Dimension(50, 50));
        btnCrudTasks.setPreferredSize(new java.awt.Dimension(25, 25));
        btnCrudTasks.addActionListener(this::btnCrudTasksActionPerformed);

        btnCrudCategories.setText("Categorias");
        btnCrudCategories.setMaximumSize(new java.awt.Dimension(50, 50));
        btnCrudCategories.setMinimumSize(new java.awt.Dimension(50, 50));
        btnCrudCategories.addActionListener(this::btnCrudCategoriesActionPerformed);

        btnCrudSessions.setText("Sessões");
        btnCrudSessions.addActionListener(this::btnCrudSessionsActionPerformed);

        javax.swing.GroupLayout CrudButtonsLayout = new javax.swing.GroupLayout(CrudButtons);
        CrudButtons.setLayout(CrudButtonsLayout);
        CrudButtonsLayout.setHorizontalGroup(
            CrudButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrudButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CrudButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnCrudSessions, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrudCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrudTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CrudButtonsLayout.setVerticalGroup(
            CrudButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrudButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCrudTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCrudCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCrudSessions, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout InitialScreenLayout = new javax.swing.GroupLayout(InitialScreen);
        InitialScreen.setLayout(InitialScreenLayout);
        InitialScreenLayout.setHorizontalGroup(
            InitialScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InitialScreenLayout.createSequentialGroup()
                .addGroup(InitialScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CrudButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        InitialScreenLayout.setVerticalGroup(
            InitialScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InitialScreenLayout.createSequentialGroup()
                .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CrudButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        SwitchPanels.addTab("tab4", InitialScreen);

        taskOptions.setAlignmentX(0.0F);
        taskOptions.setAlignmentY(0.0F);
        taskOptions.setMaximumSize(new java.awt.Dimension(600, 150));
        taskOptions.setMinimumSize(new java.awt.Dimension(600, 150));
        taskOptions.setPreferredSize(new java.awt.Dimension(600, 150));

        lblTask.setText("Tarefas");

        boxTasks.addActionListener(this::boxTasksActionPerformed);

        btnStartTask.setText("Iniciar");
        btnStartTask.addActionListener(this::btnStartTaskActionPerformed);

        lblDuration.setText("Duração (min):");

        txtTaskDuration.addActionListener(this::txtTaskDurationActionPerformed);

        lblTimer.setFont(new java.awt.Font("JetBrainsMono NF", 1, 24)); // NOI18N
        lblTimer.setText("00:00");
        lblTimer.setEnabled(false);

        progressDuration.setBackground(new java.awt.Color(255, 255, 255));
        progressDuration.setToolTipText("0");
        progressDuration.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        progressDuration.setEnabled(false);
        progressDuration.setStringPainted(true);

        txtStatus.setText("Status: -");
        txtStatus.setEnabled(false);
        txtStatus.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        txtStatus.setMaximumSize(new java.awt.Dimension(148, 16));
        txtStatus.setMinimumSize(new java.awt.Dimension(148, 16));
        txtStatus.setPreferredSize(new java.awt.Dimension(148, 16));

        btnReturnInitialTask.setText("Pausar");
        btnReturnInitialTask.setEnabled(false);
        btnReturnInitialTask.addActionListener(this::btnReturnInitialTaskActionPerformed);

        btnReturnInitialTask1.setText("Sair");
        btnReturnInitialTask1.addActionListener(this::btnReturnInitialTask1ActionPerformed);

        btnReturnInitialTask2.setText("Parar");
        btnReturnInitialTask2.setEnabled(false);
        btnReturnInitialTask2.addActionListener(this::btnReturnInitialTask2ActionPerformed);

        btnReturnInitialTask3.setText("Voltar");
        btnReturnInitialTask3.addActionListener(this::btnReturnInitialTask3ActionPerformed);

        javax.swing.GroupLayout taskOptionsLayout = new javax.swing.GroupLayout(taskOptions);
        taskOptions.setLayout(taskOptionsLayout);
        taskOptionsLayout.setHorizontalGroup(
            taskOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(taskOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(taskOptionsLayout.createSequentialGroup()
                        .addGroup(taskOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTask)
                            .addComponent(lblDuration))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(taskOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxTasks, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTaskDuration)))
                    .addGroup(taskOptionsLayout.createSequentialGroup()
                        .addComponent(btnReturnInitialTask3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReturnInitialTask1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(taskOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(taskOptionsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnReturnInitialTask2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(taskOptionsLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(taskOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnStartTask, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(btnReturnInitialTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(taskOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progressDuration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(69, 69, 69))
        );

        taskOptionsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnReturnInitialTask3, lblDuration, lblTask});

        taskOptionsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {boxTasks, btnReturnInitialTask1, txtTaskDuration});

        taskOptionsLayout.setVerticalGroup(
            taskOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskOptionsLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(taskOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxTasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTask)
                    .addComponent(btnStartTask)
                    .addComponent(lblTimer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(taskOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTaskDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDuration)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReturnInitialTask))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(taskOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(taskOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnReturnInitialTask3)
                        .addComponent(btnReturnInitialTask1)
                        .addComponent(btnReturnInitialTask2))
                    .addGroup(taskOptionsLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(progressDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnStartTask.getAccessibleContext().setAccessibleDescription("");

        taskContent.setMaximumSize(new java.awt.Dimension(600, 300));
        taskContent.setMinimumSize(new java.awt.Dimension(600, 300));
        taskContent.setPreferredSize(new java.awt.Dimension(600, 300));

        taskScrollPane.setMaximumSize(new java.awt.Dimension(600, 300));
        taskScrollPane.setMinimumSize(new java.awt.Dimension(600, 300));
        taskScrollPane.setPreferredSize(new java.awt.Dimension(600, 300));

        taskTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        taskScrollPane.setViewportView(taskTable);

        javax.swing.GroupLayout taskContentLayout = new javax.swing.GroupLayout(taskContent);
        taskContent.setLayout(taskContentLayout);
        taskContentLayout.setHorizontalGroup(
            taskContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taskScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        taskContentLayout.setVerticalGroup(
            taskContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskContentLayout.createSequentialGroup()
                .addComponent(taskScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TaskScreenLayout = new javax.swing.GroupLayout(TaskScreen);
        TaskScreen.setLayout(TaskScreenLayout);
        TaskScreenLayout.setHorizontalGroup(
            TaskScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaskScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taskOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(TaskScreenLayout.createSequentialGroup()
                .addComponent(taskContent, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        TaskScreenLayout.setVerticalGroup(
            TaskScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaskScreenLayout.createSequentialGroup()
                .addComponent(taskOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taskContent, javax.swing.GroupLayout.PREFERRED_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );

        SwitchPanels.addTab("tab1", TaskScreen);

        categoryOptions.setMaximumSize(new java.awt.Dimension(600, 100));
        categoryOptions.setMinimumSize(new java.awt.Dimension(600, 100));
        categoryOptions.setPreferredSize(new java.awt.Dimension(600, 100));

        btnCreateTask1.setText("Criar");
        btnCreateTask1.addActionListener(this::btnCreateTask1ActionPerformed);

        btnUpdateTask1.setText("Atualizar");
        btnUpdateTask1.addActionListener(this::btnUpdateTask1ActionPerformed);

        btnDeleteTask1.setText("Excluir");
        btnDeleteTask1.addActionListener(this::btnDeleteTask1ActionPerformed);

        btnReturnInitialTask5.setText("Sair");
        btnReturnInitialTask5.addActionListener(this::btnReturnInitialTask5ActionPerformed);

        btnReturnInitialTask7.setText("Voltar");
        btnReturnInitialTask7.addActionListener(this::btnReturnInitialTask7ActionPerformed);

        javax.swing.GroupLayout categoryOptionsLayout = new javax.swing.GroupLayout(categoryOptions);
        categoryOptions.setLayout(categoryOptionsLayout);
        categoryOptionsLayout.setHorizontalGroup(
            categoryOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoryOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(categoryOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(categoryOptionsLayout.createSequentialGroup()
                        .addComponent(btnReturnInitialTask7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReturnInitialTask5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(categoryOptionsLayout.createSequentialGroup()
                        .addComponent(btnCreateTask1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateTask1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteTask1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(342, Short.MAX_VALUE))
        );
        categoryOptionsLayout.setVerticalGroup(
            categoryOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, categoryOptionsLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(categoryOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturnInitialTask7)
                    .addComponent(btnReturnInitialTask5))
                .addGap(18, 18, 18)
                .addGroup(categoryOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateTask1)
                    .addComponent(btnDeleteTask1)
                    .addComponent(btnCreateTask1))
                .addContainerGap())
        );

        categoryContent.setAlignmentX(0.0F);
        categoryContent.setAlignmentY(0.0F);
        categoryContent.setMaximumSize(new java.awt.Dimension(600, 300));
        categoryContent.setMinimumSize(new java.awt.Dimension(600, 300));
        categoryContent.setPreferredSize(new java.awt.Dimension(600, 300));

        categoryScrollPane.setAlignmentX(0.0F);
        categoryScrollPane.setAlignmentY(0.0F);
        categoryScrollPane.setMaximumSize(new java.awt.Dimension(600, 300));
        categoryScrollPane.setMinimumSize(new java.awt.Dimension(600, 300));
        categoryScrollPane.setPreferredSize(new java.awt.Dimension(600, 300));

        categoryTable.setAlignmentX(0.0F);
        categoryTable.setAlignmentY(0.0F);
        categoryTable.setMaximumSize(new java.awt.Dimension(600, 80));
        categoryTable.setMinimumSize(new java.awt.Dimension(600, 80));
        categoryTable.setPreferredSize(new java.awt.Dimension(600, 80));
        categoryScrollPane.setViewportView(categoryTable);

        javax.swing.GroupLayout categoryContentLayout = new javax.swing.GroupLayout(categoryContent);
        categoryContent.setLayout(categoryContentLayout);
        categoryContentLayout.setHorizontalGroup(
            categoryContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoryContentLayout.createSequentialGroup()
                .addComponent(categoryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap())
        );
        categoryContentLayout.setVerticalGroup(
            categoryContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoryContentLayout.createSequentialGroup()
                .addComponent(categoryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout CategoryScreenLayout = new javax.swing.GroupLayout(CategoryScreen);
        CategoryScreen.setLayout(CategoryScreenLayout);
        CategoryScreenLayout.setHorizontalGroup(
            CategoryScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoryScreenLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(categoryContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(categoryOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        CategoryScreenLayout.setVerticalGroup(
            CategoryScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoryScreenLayout.createSequentialGroup()
                .addComponent(categoryOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoryContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        SwitchPanels.addTab("tab2", CategoryScreen);

        sessionOptions.setMaximumSize(new java.awt.Dimension(600, 100));
        sessionOptions.setMinimumSize(new java.awt.Dimension(600, 100));

        javax.swing.GroupLayout sessionOptionsLayout = new javax.swing.GroupLayout(sessionOptions);
        sessionOptions.setLayout(sessionOptionsLayout);
        sessionOptionsLayout.setHorizontalGroup(
            sessionOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        sessionOptionsLayout.setVerticalGroup(
            sessionOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        sessionContent.setAlignmentX(0.0F);
        sessionContent.setAlignmentY(0.0F);
        sessionContent.setMaximumSize(new java.awt.Dimension(600, 300));
        sessionContent.setMinimumSize(new java.awt.Dimension(600, 300));

        sessionScrollPane.setAlignmentX(0.0F);
        sessionScrollPane.setAlignmentY(0.0F);
        sessionScrollPane.setMaximumSize(new java.awt.Dimension(600, 300));
        sessionScrollPane.setMinimumSize(new java.awt.Dimension(600, 300));
        sessionScrollPane.setPreferredSize(new java.awt.Dimension(600, 300));

        sessionTable.setAlignmentX(0.0F);
        sessionTable.setAlignmentY(0.0F);
        sessionTable.setMaximumSize(new java.awt.Dimension(600, 80));
        sessionTable.setMinimumSize(new java.awt.Dimension(600, 80));
        sessionTable.setPreferredSize(new java.awt.Dimension(600, 80));
        sessionScrollPane.setViewportView(sessionTable);

        javax.swing.GroupLayout sessionContentLayout = new javax.swing.GroupLayout(sessionContent);
        sessionContent.setLayout(sessionContentLayout);
        sessionContentLayout.setHorizontalGroup(
            sessionContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sessionContentLayout.createSequentialGroup()
                .addComponent(sessionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap())
        );
        sessionContentLayout.setVerticalGroup(
            sessionContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sessionContentLayout.createSequentialGroup()
                .addComponent(sessionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout SessionScreenLayout = new javax.swing.GroupLayout(SessionScreen);
        SessionScreen.setLayout(SessionScreenLayout);
        SessionScreenLayout.setHorizontalGroup(
            SessionScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SessionScreenLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(sessionContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(sessionOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        SessionScreenLayout.setVerticalGroup(
            SessionScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SessionScreenLayout.createSequentialGroup()
                .addComponent(sessionOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sessionContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        SwitchPanels.addTab("tab2", SessionScreen);

        javax.swing.GroupLayout taskRegisterPanelLayout = new javax.swing.GroupLayout(taskRegisterPanel);
        taskRegisterPanel.setLayout(taskRegisterPanelLayout);
        taskRegisterPanelLayout.setHorizontalGroup(
            taskRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        taskRegisterPanelLayout.setVerticalGroup(
            taskRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        SwitchPanels.addTab("tab5", taskRegisterPanel);

        javax.swing.GroupLayout categoryRegisterPanelLayout = new javax.swing.GroupLayout(categoryRegisterPanel);
        categoryRegisterPanel.setLayout(categoryRegisterPanelLayout);
        categoryRegisterPanelLayout.setHorizontalGroup(
            categoryRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        categoryRegisterPanelLayout.setVerticalGroup(
            categoryRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        SwitchPanels.addTab("tab5", categoryRegisterPanel);

        javax.swing.GroupLayout sessionRegisterPanelLayout = new javax.swing.GroupLayout(sessionRegisterPanel);
        sessionRegisterPanel.setLayout(sessionRegisterPanelLayout);
        sessionRegisterPanelLayout.setHorizontalGroup(
            sessionRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        sessionRegisterPanelLayout.setVerticalGroup(
            sessionRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        SwitchPanels.addTab("tab5", sessionRegisterPanel);

        getContentPane().add(SwitchPanels, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -36, 600, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrudTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrudTasksActionPerformed
        // TODO add your handling code here:
        switchScreens("Tasks", SwitchPanels);
    }//GEN-LAST:event_btnCrudTasksActionPerformed

    private void btnCrudSessionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrudSessionsActionPerformed
        // TODO add your handling code here:
        switchScreens("Sessions", SwitchPanels);
    }//GEN-LAST:event_btnCrudSessionsActionPerformed

    private void btnCrudCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrudCategoriesActionPerformed
        // TODO add your handling code here:
        switchScreens("Categories", SwitchPanels);
    }//GEN-LAST:event_btnCrudCategoriesActionPerformed

    private void btnStartTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStartTaskActionPerformed

    private void txtTaskDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaskDurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTaskDurationActionPerformed

    private void boxTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTasksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxTasksActionPerformed

    private void btnReturnInitialTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnInitialTaskActionPerformed
        // TODO add your handling code here:
        switchScreens("Initial", SwitchPanels);
    }//GEN-LAST:event_btnReturnInitialTaskActionPerformed

    private void btnReturnInitialTask1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnInitialTask1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReturnInitialTask1ActionPerformed

    private void btnReturnInitialTask2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnInitialTask2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReturnInitialTask2ActionPerformed

    private void btnReturnInitialTask3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnInitialTask3ActionPerformed
        // TODO add your handling code here:
        switchScreens("Initial", SwitchPanels);
    }//GEN-LAST:event_btnReturnInitialTask3ActionPerformed

    private void btnCreateTask1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTask1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateTask1ActionPerformed

    private void btnUpdateTask1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTask1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateTask1ActionPerformed

    private void btnDeleteTask1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTask1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteTask1ActionPerformed

    private void btnReturnInitialTask5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnInitialTask5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReturnInitialTask5ActionPerformed

    private void btnReturnInitialTask7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnInitialTask7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReturnInitialTask7ActionPerformed

    private void loadCategories() {
        List<CategoryResponse> categories = categoryController.findAll();
        boxTasks.removeAllItems();
        for (CategoryResponse category : categories) {
            boxTasks.addItem(category.getName());
        }
    }
    
    private void switchScreens(String currentScreen, JTabbedPane jTabbedPane) {
        switch(currentScreen) {
            case "Initial": jTabbedPane.setSelectedIndex(0);
                break;
            case "Tasks":
                jTabbedPane.setSelectedIndex(1);
                break;
            case "Categories":
                jTabbedPane.setSelectedIndex(2);
                break;
            case "Sessions":
                jTabbedPane.setSelectedIndex(3);
                break;
            case "TaskRegister":
                jTabbedPane.setSelectedIndex(4);
                break;
            case "CategoryRegister":
                jTabbedPane.setSelectedIndex(5);
                break;
            case "SessionRegister":
                jTabbedPane.setSelectedIndex(6);
                break;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CategoryScreen;
    private javax.swing.JPanel CrudButtons;
    private javax.swing.JPanel InitialScreen;
    private javax.swing.JPanel Logo;
    private javax.swing.JPanel SessionScreen;
    private javax.swing.JTabbedPane SwitchPanels;
    private javax.swing.JPanel TaskScreen;
    private javax.swing.JComboBox<String> boxTasks;
    private javax.swing.JButton btnCreateTask1;
    private javax.swing.JButton btnCrudCategories;
    private javax.swing.JButton btnCrudSessions;
    private javax.swing.JButton btnCrudTasks;
    private javax.swing.JButton btnDeleteTask1;
    private javax.swing.JButton btnReturnInitialTask;
    private javax.swing.JButton btnReturnInitialTask1;
    private javax.swing.JButton btnReturnInitialTask2;
    private javax.swing.JButton btnReturnInitialTask3;
    private javax.swing.JButton btnReturnInitialTask5;
    private javax.swing.JButton btnReturnInitialTask7;
    private javax.swing.JButton btnStartTask;
    private javax.swing.JButton btnUpdateTask1;
    private javax.swing.JPanel categoryContent;
    private javax.swing.JPanel categoryOptions;
    private javax.swing.JPanel categoryRegisterPanel;
    private javax.swing.JScrollPane categoryScrollPane;
    private javax.swing.JTable categoryTable;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblTask;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JProgressBar progressDuration;
    private javax.swing.JPanel sessionContent;
    private javax.swing.JPanel sessionOptions;
    private javax.swing.JPanel sessionRegisterPanel;
    private javax.swing.JScrollPane sessionScrollPane;
    private javax.swing.JTable sessionTable;
    private javax.swing.JPanel taskContent;
    private javax.swing.JPanel taskOptions;
    private javax.swing.JPanel taskRegisterPanel;
    private javax.swing.JScrollPane taskScrollPane;
    private javax.swing.JTable taskTable;
    private javax.swing.JLabel txtStatus;
    private javax.swing.JTextField txtTaskDuration;
    // End of variables declaration//GEN-END:variables
}
