/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.view;

import br.com.controller.CategoryController;
import br.com.controller.TaskController;
import br.com.controller.PomodoroSessionController;
import br.com.dto.category.CategoryRequest;
import br.com.dto.category.CategoryResponse;
import br.com.dto.task.TaskResponse;
import br.com.dto.task.TaskRequest;
import br.com.dto.pomodoroSession.PomodoroSessionRequest;
import br.com.dto.pomodoroSession.PomodoroSessionResponse;
import br.com.table.CategoryTableModel;
import br.com.table.TaskTableModel;
import br.com.table.PomodoroSessionTableModel;

import java.awt.Component;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author gabrielnathan
 */
public class MainScreen extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainScreen.class.getName());
    // Controllers
    private final TaskController taskController = new TaskController();
    private final CategoryController categoryController = new CategoryController();
    private final PomodoroSessionController pomodoroSessionController = new PomodoroSessionController();
    // Responses
    private TaskResponse taskResponse;
    private CategoryResponse categoryResponse;
    // Tables
    private TaskTableModel taskTableModel;
    private CategoryTableModel categoryTableModel;
    private PomodoroSessionTableModel pomodoroSessionTableModel;
    // Timer variables
    private javax.swing.Timer pomodoroTimer;
    private int totalSeconds;
    private int elapsedSeconds;
    private boolean isPaused;
    private Date sessionStartTime;

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        setLocationRelativeTo(null);
        loadTasks();
        loadCategories();
        loadSessionPomodoro();
        setTaskComboBox(boxTasks);
        setCategoryComboBox(categoryBox);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SwitchPanels = new javax.swing.JTabbedPane();
        InitialScreen = new javax.swing.JPanel();
        Logo = new javax.swing.JPanel();
        lblProgram = new javax.swing.JLabel();
        CrudButtons = new javax.swing.JPanel();
        btnCrudTasks = new javax.swing.JButton();
        btnCrudCategories = new javax.swing.JButton();
        btnCrudSessions = new javax.swing.JButton();
        btnStartProgram = new javax.swing.JButton();
        StartProgram = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        lblTask = new javax.swing.JLabel();
        boxTasks = new javax.swing.JComboBox<>();
        btnStartTask = new javax.swing.JButton();
        lblDuration = new javax.swing.JLabel();
        txtTaskDuration = new javax.swing.JTextField();
        lblTimer = new javax.swing.JLabel();
        progressDuration = new javax.swing.JProgressBar();
        txtStatus = new javax.swing.JLabel();
        btnPauseTask = new javax.swing.JButton();
        btnExitProgram = new javax.swing.JButton();
        btnStopTask = new javax.swing.JButton();
        btnReturnInitialTask = new javax.swing.JButton();
        TaskScreen = new javax.swing.JPanel();
        taskOptions = new javax.swing.JPanel();
        btnCreateTask = new javax.swing.JButton();
        btnUpdateTask = new javax.swing.JButton();
        btnDeleteTask = new javax.swing.JButton();
        btnExitTask = new javax.swing.JButton();
        btnReturnTask = new javax.swing.JButton();
        taskContent = new javax.swing.JPanel();
        taskScrollPane = new javax.swing.JScrollPane();
        taskTable = new javax.swing.JTable();
        CategoryScreen = new javax.swing.JPanel();
        categoryOptions = new javax.swing.JPanel();
        btnCreateCategory = new javax.swing.JButton();
        btnUpdateCategory = new javax.swing.JButton();
        btnDeleteCategory = new javax.swing.JButton();
        btnExitCategory = new javax.swing.JButton();
        btnReturnCategory = new javax.swing.JButton();
        categoryContent = new javax.swing.JPanel();
        categoryScrollPane = new javax.swing.JScrollPane();
        categoryTable = new javax.swing.JTable();
        SessionScreen = new javax.swing.JPanel();
        sessionOptions = new javax.swing.JPanel();
        btnExitSession = new javax.swing.JButton();
        btnReturnSession = new javax.swing.JButton();
        sessionContent = new javax.swing.JPanel();
        sessionScrollPane = new javax.swing.JScrollPane();
        sessionTable = new javax.swing.JTable();
        taskRegisterScreen = new javax.swing.JPanel();
        taskRegisterPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        txtTitleTask = new javax.swing.JTextField();
        txtDescriptionTask = new javax.swing.JTextField();
        btnRegisterTask = new javax.swing.JButton();
        categoryBox = new javax.swing.JComboBox<>();
        categoryRegisterScreen = new javax.swing.JPanel();
        categoryRegisterPanel = new javax.swing.JPanel();
        lblNameCategory = new javax.swing.JLabel();
        lblDescriptionCategory = new javax.swing.JLabel();
        txtNameCategory = new javax.swing.JTextField();
        txtDescriptionCategory = new javax.swing.JTextField();
        btnRegisterCategory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setName("MainFrame"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SwitchPanels.setMaximumSize(new java.awt.Dimension(800, 400));
        SwitchPanels.setMinimumSize(new java.awt.Dimension(800, 400));
        SwitchPanels.setPreferredSize(new java.awt.Dimension(800, 400));

        InitialScreen.setPreferredSize(new java.awt.Dimension(600, 400));

        Logo.setPreferredSize(new java.awt.Dimension(600, 150));

        lblProgram.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblProgram.setText("Pomodoro");
        lblProgram.setAlignmentY(0.0F);

        javax.swing.GroupLayout LogoLayout = new javax.swing.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
                LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LogoLayout.createSequentialGroup()
                                .addContainerGap(254, Short.MAX_VALUE)
                                .addComponent(lblProgram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap(255, Short.MAX_VALUE))
        );
        LogoLayout.setVerticalGroup(
                LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoLayout.createSequentialGroup()
                                .addContainerGap(73, Short.MAX_VALUE)
                                .addComponent(lblProgram)
                                .addContainerGap(44, Short.MAX_VALUE))
        );

        CrudButtons.setPreferredSize(new java.awt.Dimension(600, 250));

        btnCrudTasks.setText("Tarefas");
        btnCrudTasks.setMaximumSize(new java.awt.Dimension(50, 50));
        btnCrudTasks.setMinimumSize(new java.awt.Dimension(50, 50));
        btnCrudTasks.setPreferredSize(new java.awt.Dimension(25, 25));
        btnCrudTasks.addActionListener(this::btnCrudTasksActionPerformed);

        btnCrudCategories.setText("Categorias");
        btnCrudCategories.setMaximumSize(new java.awt.Dimension(50, 50));
        btnCrudCategories.setMinimumSize(new java.awt.Dimension(50, 50));
        btnCrudCategories.addActionListener(this::btnCrudCategoriesActionPerformed);

        btnCrudSessions.setText("Sessões");
        btnCrudSessions.addActionListener(this::btnCrudSessionsActionPerformed);

        btnStartProgram.setText("Iniciar Sessão");
        btnStartProgram.addActionListener(this::btnStartProgramActionPerformed);

        javax.swing.GroupLayout CrudButtonsLayout = new javax.swing.GroupLayout(CrudButtons);
        CrudButtons.setLayout(CrudButtonsLayout);
        CrudButtonsLayout.setHorizontalGroup(
                CrudButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CrudButtonsLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(CrudButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(btnCrudSessions, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCrudCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCrudTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnStartProgram))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CrudButtonsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]{btnCrudCategories, btnCrudSessions, btnCrudTasks, btnStartProgram});

        CrudButtonsLayout.setVerticalGroup(
                CrudButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CrudButtonsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnStartProgram)
                                .addGap(9, 9, 9)
                                .addComponent(btnCrudTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCrudCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCrudSessions, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout InitialScreenLayout = new javax.swing.GroupLayout(InitialScreen);
        InitialScreen.setLayout(InitialScreenLayout);
        InitialScreenLayout.setHorizontalGroup(
                InitialScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InitialScreenLayout.createSequentialGroup()
                                .addGroup(InitialScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CrudButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, 0))
        );
        InitialScreenLayout.setVerticalGroup(
                InitialScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InitialScreenLayout.createSequentialGroup()
                                .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CrudButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0))
        );

        SwitchPanels.addTab("tab4", InitialScreen);

        StartProgram.setMaximumSize(new java.awt.Dimension(600, 400));
        StartProgram.setMinimumSize(new java.awt.Dimension(600, 400));
        StartProgram.setPreferredSize(new java.awt.Dimension(600, 400));

        content.setAlignmentX(0.0F);
        content.setAlignmentY(0.0F);
        content.setMaximumSize(new java.awt.Dimension(600, 400));
        content.setMinimumSize(new java.awt.Dimension(600, 150));

        lblTask.setText("Tarefas");

        boxTasks.addActionListener(this::boxTasksActionPerformed);

        btnStartTask.setText("Iniciar");
        btnStartTask.addActionListener(this::btnStartTaskActionPerformed);

        lblDuration.setText("Duração (min):");

        txtTaskDuration.addActionListener(this::txtTaskDurationActionPerformed);

        lblTimer.setFont(new java.awt.Font("JetBrainsMono NF", 1, 24)); // NOI18N
        lblTimer.setText("00:00");
        lblTimer.setEnabled(false);
        lblTimer.setPreferredSize(new java.awt.Dimension(148, 33));

        progressDuration.setBackground(new java.awt.Color(255, 255, 255));
        progressDuration.setToolTipText("0");
        progressDuration.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        progressDuration.setEnabled(false);
        progressDuration.setStringPainted(true);

        txtStatus.setText("Status: -");
        txtStatus.setEnabled(false);
        txtStatus.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        txtStatus.setMaximumSize(new java.awt.Dimension(148, 15));
        txtStatus.setMinimumSize(new java.awt.Dimension(148, 15));
        txtStatus.setPreferredSize(new java.awt.Dimension(148, 15));

        btnPauseTask.setText("Pausar");
        btnPauseTask.setEnabled(false);
        btnPauseTask.addActionListener(this::btnPauseTaskActionPerformed);

        btnExitProgram.setText("Sair");
        btnExitProgram.addActionListener(this::btnExitProgramActionPerformed);

        btnStopTask.setText("Parar");
        btnStopTask.setEnabled(false);
        btnStopTask.addActionListener(this::btnStopTaskActionPerformed);

        btnReturnInitialTask.setText("Voltar");
        btnReturnInitialTask.addActionListener(this::btnReturnInitialTaskActionPerformed);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
                contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                                .addContainerGap(154, Short.MAX_VALUE)
                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(progressDuration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(contentLayout.createSequentialGroup()
                                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(contentLayout.createSequentialGroup()
                                                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lblTask)
                                                                        .addComponent(lblDuration))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(boxTasks, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(txtTaskDuration)))
                                                        .addGroup(contentLayout.createSequentialGroup()
                                                                .addComponent(btnReturnInitialTask, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btnExitProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(50, 50, 50)
                                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(btnStartTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnPauseTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnStopTask, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(txtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(153, Short.MAX_VALUE))
        );

        contentLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]{btnReturnInitialTask, lblDuration, lblTask});

        contentLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]{boxTasks, btnExitProgram, txtTaskDuration});

        contentLayout.setVerticalGroup(
                contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(contentLayout.createSequentialGroup()
                                .addContainerGap(98, Short.MAX_VALUE)
                                .addComponent(lblTimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(progressDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(boxTasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblTask)
                                        .addComponent(btnStartTask))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtTaskDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblDuration)
                                        .addComponent(btnPauseTask))
                                .addGap(0, 37, Short.MAX_VALUE)
                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnReturnInitialTask)
                                        .addComponent(btnExitProgram)
                                        .addComponent(btnStopTask))
                                .addContainerGap(112, Short.MAX_VALUE))
        );

        btnStartTask.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout StartProgramLayout = new javax.swing.GroupLayout(StartProgram);
        StartProgram.setLayout(StartProgramLayout);
        StartProgramLayout.setHorizontalGroup(
                StartProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        StartProgramLayout.setVerticalGroup(
                StartProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StartProgramLayout.createSequentialGroup()
                                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SwitchPanels.addTab("tab1", StartProgram);

        TaskScreen.setMaximumSize(new java.awt.Dimension(600, 400));
        TaskScreen.setMinimumSize(new java.awt.Dimension(600, 400));
        TaskScreen.setPreferredSize(new java.awt.Dimension(600, 400));

        taskOptions.setMaximumSize(new java.awt.Dimension(600, 100));
        taskOptions.setMinimumSize(new java.awt.Dimension(600, 100));

        btnCreateTask.setText("Criar");
        btnCreateTask.addActionListener(this::btnCreateTaskActionPerformed);

        btnUpdateTask.setText("Atualizar");
        btnUpdateTask.addActionListener(this::btnUpdateTaskActionPerformed);

        btnDeleteTask.setText("Excluir");
        btnDeleteTask.addActionListener(this::btnDeleteTaskActionPerformed);

        btnExitTask.setText("Sair");
        btnExitTask.addActionListener(this::btnExitTaskActionPerformed);

        btnReturnTask.setText("Voltar");
        btnReturnTask.addActionListener(this::btnReturnTaskActionPerformed);

        javax.swing.GroupLayout taskOptionsLayout = new javax.swing.GroupLayout(taskOptions);
        taskOptions.setLayout(taskOptionsLayout);
        taskOptionsLayout.setHorizontalGroup(
                taskOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(taskOptionsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(taskOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(taskOptionsLayout.createSequentialGroup()
                                                .addComponent(btnReturnTask, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnExitTask, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(taskOptionsLayout.createSequentialGroup()
                                                .addComponent(btnCreateTask, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnUpdateTask, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnDeleteTask, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(342, Short.MAX_VALUE))
        );
        taskOptionsLayout.setVerticalGroup(
                taskOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taskOptionsLayout.createSequentialGroup()
                                .addContainerGap(32, Short.MAX_VALUE)
                                .addGroup(taskOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnReturnTask)
                                        .addComponent(btnExitTask))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(taskOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnUpdateTask)
                                        .addComponent(btnDeleteTask)
                                        .addComponent(btnCreateTask))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        taskContent.setAlignmentX(0.0F);
        taskContent.setAlignmentY(0.0F);
        taskContent.setMaximumSize(new java.awt.Dimension(600, 300));
        taskContent.setMinimumSize(new java.awt.Dimension(600, 300));

        taskScrollPane.setAlignmentX(0.0F);
        taskScrollPane.setAlignmentY(0.0F);
        taskScrollPane.setMaximumSize(new java.awt.Dimension(600, 300));
        taskScrollPane.setMinimumSize(new java.awt.Dimension(600, 300));
        taskScrollPane.setPreferredSize(new java.awt.Dimension(600, 300));

        taskTable.setAlignmentX(0.0F);
        taskTable.setAlignmentY(0.0F);
        taskScrollPane.setViewportView(taskTable);

        javax.swing.GroupLayout taskContentLayout = new javax.swing.GroupLayout(taskContent);
        taskContent.setLayout(taskContentLayout);
        taskContentLayout.setHorizontalGroup(
                taskContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(taskContentLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(taskScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 588, Short.MAX_VALUE)
                                .addContainerGap())
        );
        taskContentLayout.setVerticalGroup(
                taskContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(taskContentLayout.createSequentialGroup()
                                .addComponent(taskScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout TaskScreenLayout = new javax.swing.GroupLayout(TaskScreen);
        TaskScreen.setLayout(TaskScreenLayout);
        TaskScreenLayout.setHorizontalGroup(
                TaskScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TaskScreenLayout.createSequentialGroup()
                                .addGroup(TaskScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(taskOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(taskContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12))
        );
        TaskScreenLayout.setVerticalGroup(
                TaskScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TaskScreenLayout.createSequentialGroup()
                                .addComponent(taskOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(taskContent, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(8, Short.MAX_VALUE))
        );

        SwitchPanels.addTab("tab2", TaskScreen);

        CategoryScreen.setMaximumSize(new java.awt.Dimension(600, 400));
        CategoryScreen.setMinimumSize(new java.awt.Dimension(600, 400));

        categoryOptions.setMaximumSize(new java.awt.Dimension(600, 100));
        categoryOptions.setMinimumSize(new java.awt.Dimension(600, 100));

        btnCreateCategory.setText("Criar");
        btnCreateCategory.addActionListener(this::btnCreateCategoryActionPerformed);

        btnUpdateCategory.setText("Atualizar");
        btnUpdateCategory.addActionListener(this::btnUpdateCategoryActionPerformed);

        btnDeleteCategory.setText("Excluir");
        btnDeleteCategory.addActionListener(this::btnDeleteCategoryActionPerformed);

        btnExitCategory.setText("Sair");
        btnExitCategory.addActionListener(this::btnExitCategoryActionPerformed);

        btnReturnCategory.setText("Voltar");
        btnReturnCategory.addActionListener(this::btnReturnCategoryActionPerformed);

        javax.swing.GroupLayout categoryOptionsLayout = new javax.swing.GroupLayout(categoryOptions);
        categoryOptions.setLayout(categoryOptionsLayout);
        categoryOptionsLayout.setHorizontalGroup(
                categoryOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(categoryOptionsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(categoryOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(categoryOptionsLayout.createSequentialGroup()
                                                .addComponent(btnReturnCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnExitCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(categoryOptionsLayout.createSequentialGroup()
                                                .addComponent(btnCreateCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnUpdateCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnDeleteCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(342, Short.MAX_VALUE))
        );
        categoryOptionsLayout.setVerticalGroup(
                categoryOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, categoryOptionsLayout.createSequentialGroup()
                                .addContainerGap(32, Short.MAX_VALUE)
                                .addGroup(categoryOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnReturnCategory)
                                        .addComponent(btnExitCategory))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(categoryOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnUpdateCategory)
                                        .addComponent(btnDeleteCategory)
                                        .addComponent(btnCreateCategory))
                                .addContainerGap(12, Short.MAX_VALUE))
        );

        categoryContent.setAlignmentX(0.0F);
        categoryContent.setAlignmentY(0.0F);
        categoryContent.setMaximumSize(new java.awt.Dimension(600, 300));
        categoryContent.setMinimumSize(new java.awt.Dimension(600, 300));

        categoryScrollPane.setAlignmentX(0.0F);
        categoryScrollPane.setAlignmentY(0.0F);
        categoryScrollPane.setMaximumSize(new java.awt.Dimension(600, 300));
        categoryScrollPane.setMinimumSize(new java.awt.Dimension(600, 300));
        categoryScrollPane.setPreferredSize(new java.awt.Dimension(600, 300));

        categoryTable.setAlignmentX(0.0F);
        categoryTable.setAlignmentY(0.0F);
        categoryScrollPane.setViewportView(categoryTable);

        javax.swing.GroupLayout categoryContentLayout = new javax.swing.GroupLayout(categoryContent);
        categoryContent.setLayout(categoryContentLayout);
        categoryContentLayout.setHorizontalGroup(
                categoryContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(categoryContentLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(categoryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 588, Short.MAX_VALUE)
                                .addContainerGap(18, Short.MAX_VALUE))
        );
        categoryContentLayout.setVerticalGroup(
                categoryContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(categoryContentLayout.createSequentialGroup()
                                .addComponent(categoryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CategoryScreenLayout = new javax.swing.GroupLayout(CategoryScreen);
        CategoryScreen.setLayout(CategoryScreenLayout);
        CategoryScreenLayout.setHorizontalGroup(
                CategoryScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CategoryScreenLayout.createSequentialGroup()
                                .addGroup(CategoryScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(categoryOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(categoryContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12))
        );
        CategoryScreenLayout.setVerticalGroup(
                CategoryScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CategoryScreenLayout.createSequentialGroup()
                                .addComponent(categoryOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(categoryContent, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
        );

        SwitchPanels.addTab("tab2", CategoryScreen);

        SessionScreen.setPreferredSize(new java.awt.Dimension(600, 400));

        sessionOptions.setMaximumSize(new java.awt.Dimension(600, 100));
        sessionOptions.setMinimumSize(new java.awt.Dimension(600, 100));
        sessionOptions.setPreferredSize(new java.awt.Dimension(600, 100));

        btnExitSession.setText("Sair");
        btnExitSession.addActionListener(this::btnExitSessionActionPerformed);

        btnReturnSession.setText("Voltar");
        btnReturnSession.addActionListener(this::btnReturnSessionActionPerformed);

        javax.swing.GroupLayout sessionOptionsLayout = new javax.swing.GroupLayout(sessionOptions);
        sessionOptions.setLayout(sessionOptionsLayout);
        sessionOptionsLayout.setHorizontalGroup(
                sessionOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sessionOptionsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnReturnSession, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExitSession, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(428, Short.MAX_VALUE))
        );
        sessionOptionsLayout.setVerticalGroup(
                sessionOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sessionOptionsLayout.createSequentialGroup()
                                .addContainerGap(31, Short.MAX_VALUE)
                                .addGroup(sessionOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnReturnSession)
                                        .addComponent(btnExitSession))
                                .addContainerGap(47, Short.MAX_VALUE))
        );

        sessionContent.setAlignmentX(0.0F);
        sessionContent.setAlignmentY(0.0F);
        sessionContent.setMaximumSize(new java.awt.Dimension(600, 300));
        sessionContent.setMinimumSize(new java.awt.Dimension(600, 300));
        sessionContent.setPreferredSize(new java.awt.Dimension(600, 300));

        sessionScrollPane.setAlignmentX(0.0F);
        sessionScrollPane.setAlignmentY(0.0F);
        sessionScrollPane.setMaximumSize(new java.awt.Dimension(600, 300));
        sessionScrollPane.setMinimumSize(new java.awt.Dimension(600, 300));
        sessionScrollPane.setPreferredSize(new java.awt.Dimension(600, 300));

        sessionTable.setAlignmentX(0.0F);
        sessionTable.setAlignmentY(0.0F);
        sessionScrollPane.setViewportView(sessionTable);

        javax.swing.GroupLayout sessionContentLayout = new javax.swing.GroupLayout(sessionContent);
        sessionContent.setLayout(sessionContentLayout);
        sessionContentLayout.setHorizontalGroup(
                sessionContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sessionContentLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(sessionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 588, Short.MAX_VALUE)
                                .addContainerGap())
        );
        sessionContentLayout.setVerticalGroup(
                sessionContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sessionContentLayout.createSequentialGroup()
                                .addComponent(sessionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 294, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout SessionScreenLayout = new javax.swing.GroupLayout(SessionScreen);
        SessionScreen.setLayout(SessionScreenLayout);
        SessionScreenLayout.setHorizontalGroup(
                SessionScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SessionScreenLayout.createSequentialGroup()
                                .addGroup(SessionScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sessionOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sessionContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12))
        );
        SessionScreenLayout.setVerticalGroup(
                SessionScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SessionScreenLayout.createSequentialGroup()
                                .addComponent(sessionOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(sessionContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        SwitchPanels.addTab("tab2", SessionScreen);

        taskRegisterScreen.setPreferredSize(new java.awt.Dimension(600, 400));

        lblTitle.setText("Título");

        lblDescription.setText("Descrição");

        lblCategory.setText("Categoria");

        txtTitleTask.addActionListener(this::txtTitleTaskActionPerformed);

        txtDescriptionTask.addActionListener(this::txtDescriptionTaskActionPerformed);

        btnRegisterTask.setText("Criar");
        btnRegisterTask.setPreferredSize(new java.awt.Dimension(64, 22));
        btnRegisterTask.addActionListener(this::btnRegisterTaskActionPerformed);

        javax.swing.GroupLayout taskRegisterPanelLayout = new javax.swing.GroupLayout(taskRegisterPanel);
        taskRegisterPanel.setLayout(taskRegisterPanelLayout);
        taskRegisterPanelLayout.setHorizontalGroup(
                taskRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(taskRegisterPanelLayout.createSequentialGroup()
                                .addGap(253, 253, 253)
                                .addGroup(taskRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                        .addComponent(lblDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                        .addComponent(txtDescriptionTask)
                                        .addComponent(btnRegisterTask, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                        .addComponent(categoryBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTitleTask, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 234, Short.MAX_VALUE))
        );

        taskRegisterPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]{btnRegisterTask, categoryBox, lblCategory, lblDescription, lblTitle, txtDescriptionTask, txtTitleTask});

        taskRegisterPanelLayout.setVerticalGroup(
                taskRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(taskRegisterPanelLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTitleTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescriptionTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(categoryBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRegisterTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(131, 131, 131))
        );

        javax.swing.GroupLayout taskRegisterScreenLayout = new javax.swing.GroupLayout(taskRegisterScreen);
        taskRegisterScreen.setLayout(taskRegisterScreenLayout);
        taskRegisterScreenLayout.setHorizontalGroup(
                taskRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(taskRegisterScreenLayout.createSequentialGroup()
                                .addComponent(taskRegisterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        taskRegisterScreenLayout.setVerticalGroup(
                taskRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taskRegisterScreenLayout.createSequentialGroup()
                                .addComponent(taskRegisterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        SwitchPanels.addTab("tab5", taskRegisterScreen);

        lblNameCategory.setText("Nome");

        lblDescriptionCategory.setText("Descrição");

        txtNameCategory.addActionListener(this::txtNameCategoryActionPerformed);

        txtDescriptionCategory.addActionListener(this::txtDescriptionCategoryActionPerformed);

        btnRegisterCategory.setText("Criar");
        btnRegisterCategory.setPreferredSize(new java.awt.Dimension(64, 22));
        btnRegisterCategory.addActionListener(this::btnRegisterCategoryActionPerformed);

        javax.swing.GroupLayout categoryRegisterPanelLayout = new javax.swing.GroupLayout(categoryRegisterPanel);
        categoryRegisterPanel.setLayout(categoryRegisterPanelLayout);
        categoryRegisterPanelLayout.setHorizontalGroup(
                categoryRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(categoryRegisterPanelLayout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addGroup(categoryRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNameCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNameCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblDescriptionCategory)
                                        .addComponent(txtDescriptionCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnRegisterCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 236, Short.MAX_VALUE))
        );

        categoryRegisterPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]{btnRegisterCategory, lblDescriptionCategory, lblNameCategory, txtDescriptionCategory, txtNameCategory});

        categoryRegisterPanelLayout.setVerticalGroup(
                categoryRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(categoryRegisterPanelLayout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(lblNameCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNameCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDescriptionCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescriptionCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRegisterCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(123, 123, 123))
        );

        javax.swing.GroupLayout categoryRegisterScreenLayout = new javax.swing.GroupLayout(categoryRegisterScreen);
        categoryRegisterScreen.setLayout(categoryRegisterScreenLayout);
        categoryRegisterScreenLayout.setHorizontalGroup(
                categoryRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(categoryRegisterScreenLayout.createSequentialGroup()
                                .addComponent(categoryRegisterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        categoryRegisterScreenLayout.setVerticalGroup(
                categoryRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, categoryRegisterScreenLayout.createSequentialGroup()
                                .addComponent(categoryRegisterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        SwitchPanels.addTab("tab5", categoryRegisterScreen);

        getContentPane().add(SwitchPanels, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -36, 600, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // ------------------------------------------ Initial Screen ---------------------------------------------------- //
    private void btnStartProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartProgramActionPerformed
        setTaskComboBox(boxTasks);
        switchScreens("Program", SwitchPanels);
    }//GEN-LAST:event_btnStartProgramActionPerformed

    private void btnCrudTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrudTasksActionPerformed
        switchScreens("Tasks", SwitchPanels);
    }//GEN-LAST:event_btnCrudTasksActionPerformed

    private void btnCrudCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrudCategoriesActionPerformed
        switchScreens("Categories", SwitchPanels);
    }//GEN-LAST:event_btnCrudCategoriesActionPerformed

    private void btnCrudSessionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrudSessionsActionPerformed
        switchScreens("Sessions", SwitchPanels);
        refreshAllTables();
    }//GEN-LAST:event_btnCrudSessionsActionPerformed

    // ------------------------------------------ Program Screen ---------------------------------------------------- //
    private void btnReturnInitialTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnInitialTaskActionPerformed
        switchScreens("Initial", SwitchPanels);
    }//GEN-LAST:event_btnReturnInitialTaskActionPerformed

    private void btnExitProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitProgramActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitProgramActionPerformed

    private void boxTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTasksActionPerformed
        // TODO: Implementar lógica se necessário
    }//GEN-LAST:event_boxTasksActionPerformed

    private void txtTaskDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaskDurationActionPerformed
        // TODO: Implementar lógica se necessário
    }//GEN-LAST:event_txtTaskDurationActionPerformed

    private void btnStartTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartTaskActionPerformed
        // Validar se uma tarefa foi selecionada
        TaskResponse selectedTask = (TaskResponse) boxTasks.getSelectedItem();
        if (selectedTask == null) {
            JOptionPane.showMessageDialog(this, "Selecione uma tarefa!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar duração
        String durationText = txtTaskDuration.getText().trim();
        if (durationText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Defina a duração em minutos!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int durationMinutes = Integer.parseInt(durationText);
            if (durationMinutes <= 0) {
                JOptionPane.showMessageDialog(this, "A duração deve ser maior que zero!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Se o timer já existe e está pausado, retomar
            if (isPaused && pomodoroTimer != null) {
                isPaused = false;
                pomodoroTimer.start();
                btnStartTask.setEnabled(false);
                btnPauseTask.setEnabled(true);
                btnStopTask.setEnabled(true);
                txtStatus.setText("Status: Em execução");
                return;
            }

            // Iniciar novo timer
            totalSeconds = durationMinutes * 60;
            elapsedSeconds = 0;
            isPaused = false;
            sessionStartTime = new Date(); // Registrar horário de início

            // Configurar progress bar
            progressDuration.setMaximum(totalSeconds);
            progressDuration.setValue(0);

            // Criar e iniciar timer
            pomodoroTimer = new javax.swing.Timer(1000, e -> {
                elapsedSeconds++;
                updateTimerDisplay();
                progressDuration.setValue(elapsedSeconds);

                if (elapsedSeconds >= totalSeconds) {
                    finishPomodoro();
                }
            });

            pomodoroTimer.start();

            // Atualizar UI
            btnStartTask.setEnabled(false);
            btnPauseTask.setEnabled(true);
            btnStopTask.setEnabled(true);
            boxTasks.setEnabled(false);
            txtTaskDuration.setEnabled(false);
            txtStatus.setText("Status: Em execução");
            lblTimer.setEnabled(true);
            updateTimerDisplay();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Duração inválida! Digite apenas números.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnStartTaskActionPerformed

    private void btnPauseTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseTaskActionPerformed
        if (pomodoroTimer != null && pomodoroTimer.isRunning()) {
            pomodoroTimer.stop();
            isPaused = true;
            btnStartTask.setEnabled(true);
            btnPauseTask.setEnabled(false);
            txtStatus.setText("Status: Pausado");
        }
    }//GEN-LAST:event_btnPauseTaskActionPerformed

    private void btnStopTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopTaskActionPerformed
        if (pomodoroTimer != null) {
            pomodoroTimer.stop();
            pomodoroTimer = null;
        }

        // Resetar variáveis
        elapsedSeconds = 0;
        totalSeconds = 0;
        isPaused = false;
        sessionStartTime = null;

        // Resetar UI
        lblTimer.setText("00:00");
        lblTimer.setEnabled(false);
        progressDuration.setValue(0);
        txtStatus.setText("Status: -");
        btnStartTask.setEnabled(true);
        btnPauseTask.setEnabled(false);
        btnStopTask.setEnabled(false);
        boxTasks.setEnabled(true);
        txtTaskDuration.setEnabled(true);
    }//GEN-LAST:event_btnStopTaskActionPerformed

    // ------------------------------------------ Task Screen ------------------------------------------------------- //
    private void btnCreateTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTaskActionPerformed
        // Limpa qualquer estado de edição anterior antes de abrir o formulário de criação
        taskResponse = null;
        txtTitleTask.setText("");
        txtDescriptionTask.setText("");
        btnRegisterTask.setText("Criar");
        // Atualiza o combo box com as categorias mais recentes
        setCategoryComboBox(categoryBox);
        // reseta seleção de categoria
        if (categoryBox.getItemCount() > 0) {
            categoryBox.setSelectedIndex(0);
        }
        switchScreens("TaskRegister", SwitchPanels);
    }//GEN-LAST:event_btnCreateTaskActionPerformed

    private void btnUpdateTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTaskActionPerformed
        int row = taskTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma tarefa para editar.", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Long id = (Long) taskTable.getValueAt(row, 0); // coluna ID
        TaskResponse task = taskController.findById(id);

        if (task == null) {
            JOptionPane.showMessageDialog(this, "Tarefa não encontrada.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Preenche os campos
        txtTitleTask.setText(task.getTitle());
        txtDescriptionTask.setText(task.getDescription() != null ? task.getDescription() : "");

        // Guarda a tarefa que está sendo editada (prepara o objeto de resposta usado pelo fluxo de salvar)
        taskResponse = new TaskResponse();
        taskResponse.setId(task.getId());
        taskResponse.setTitle(task.getTitle());
        taskResponse.setDescription(task.getDescription());
        taskResponse.setCategoryId(task.getCategoryId());

        // Atualiza o combo box com as categorias mais recentes
        setCategoryComboBox(categoryBox);

        // Seleciona a categoria correta no combo box (se existir)
        if (task.getCategoryId() != null) {
            for (int i = 0; i < categoryBox.getItemCount(); i++) {
                CategoryResponse item = categoryBox.getItemAt(i);
                if (item != null && item.getId() != null && item.getId().equals(task.getCategoryId())) {
                    categoryBox.setSelectedIndex(i);
                    break;
                }
            }
        } else {
            categoryBox.setSelectedIndex(-1);
        }

        // Muda o botão para indicar edição
        btnRegisterTask.setText("Salvar Alterações");

        // Abre a tela de cadastro com os dados preenchidos
        switchScreens("TaskRegister", SwitchPanels);
    }//GEN-LAST:event_btnUpdateTaskActionPerformed

    private void btnDeleteTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTaskActionPerformed
        int row = taskTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma tarefa.");
            return;
        }

        Long id = (Long) taskTable.getValueAt(row, 0);

        if (JOptionPane.showConfirmDialog(this, "Excluir tarefa?") == 0) {
            taskController.delete(id);
            loadTasks();
            setTaskComboBox(boxTasks);
        }
    }//GEN-LAST:event_btnDeleteTaskActionPerformed

    private void btnExitTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitTaskActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitTaskActionPerformed

    private void btnReturnTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnTaskActionPerformed
        switchScreens("Initial", SwitchPanels);
    }//GEN-LAST:event_btnReturnTaskActionPerformed

    private void txtTitleTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitleTaskActionPerformed
        // TODO: Implementar lógica se necessário
    }//GEN-LAST:event_txtTitleTaskActionPerformed

    private void txtDescriptionTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionTaskActionPerformed
        // TODO: Implementar lógica se necessário
    }//GEN-LAST:event_txtDescriptionTaskActionPerformed

    // ------------------------------------------ Task Register ----------------------------------------------------- //
    private void btnRegisterTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterTaskActionPerformed
        String title = txtTitleTask.getText().trim();
        String description = txtDescriptionTask.getText().trim();

        if (title.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O título da tarefa é obrigatório!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        CategoryResponse selectedCategory = (CategoryResponse) categoryBox.getSelectedItem();
        if (selectedCategory == null) {
            JOptionPane.showMessageDialog(this, "Selecione uma categoria!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            TaskRequest request = new TaskRequest();
            request.setTitle(title);
            request.setDescription(description.isEmpty() ? null : description);
            request.setCategoryId(selectedCategory.getId());

            if (taskResponse == null) {
                taskController.create(request);
                JOptionPane.showMessageDialog(this, "Tarefa criada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            } else {
                taskController.update(taskResponse.getId(), request);
                JOptionPane.showMessageDialog(this, "Tarefa atualizada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                taskResponse = null;
                btnRegisterTask.setText("Criar");
            }
            refreshAllTables();
            setTaskComboBox(boxTasks);
            switchScreens("Tasks", SwitchPanels);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar tarefa: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            logger.severe("Erro ao salvar tarefa: " + e.getMessage());
        }
    }//GEN-LAST:event_btnRegisterTaskActionPerformed

    // ------------------------------------------ Category Screen --------------------------------------------------- //
    private void btnCreateCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCategoryActionPerformed
        // Limpa estado de edição de categoria ao abrir criação
        categoryResponse = null;
        txtNameCategory.setText("");
        txtDescriptionCategory.setText("");
        btnRegisterCategory.setText("Criar");
        switchScreens("CategoryRegister", SwitchPanels);
    }//GEN-LAST:event_btnCreateCategoryActionPerformed

    private void btnUpdateCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCategoryActionPerformed
        int row = categoryTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma categoria para editar.", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Long id = (Long) categoryTable.getValueAt(row, 0); // coluna ID
        CategoryResponse category = categoryController.findById(id);

        if (category == null) {
            JOptionPane.showMessageDialog(this, "Tarefa não encontrada.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Preenche os campos
        txtNameCategory.setText(category.getName());
        txtDescriptionCategory.setText(category.getDescription() != null ? category.getDescription() : "");

        // Guarda a categoria que está sendo editada (prepara o objeto de resposta usado pelo fluxo de salvar)
        categoryResponse = new CategoryResponse();
        categoryResponse.setId(category.getId());
        categoryResponse.setName(category.getName());
        categoryResponse.setDescription(category.getDescription());

        // Muda o botão para indicar edição
        btnRegisterCategory.setText("Salvar Alterações");

        // Abre a tela de cadastro com os dados preenchidos
        switchScreens("CategoryRegister", SwitchPanels);
    }//GEN-LAST:event_btnUpdateCategoryActionPerformed

    private void btnDeleteCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCategoryActionPerformed
        int row = categoryTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma categoria.");
            return;
        }

        Long id = (Long) categoryTable.getValueAt(row, 0);

        if (JOptionPane.showConfirmDialog(this, "Excluir categoria?") == 0) {
            categoryController.delete(id);
            loadCategories();
            setCategoryComboBox(categoryBox);
        }
    }//GEN-LAST:event_btnDeleteCategoryActionPerformed

    private void btnExitCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitCategoryActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitCategoryActionPerformed

    private void btnReturnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnCategoryActionPerformed
        switchScreens("Initial", SwitchPanels);
    }//GEN-LAST:event_btnReturnCategoryActionPerformed

    // ------------------------------------------ Category Register ------------------------------------------------- //
    private void txtNameCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameCategoryActionPerformed
    }//GEN-LAST:event_txtNameCategoryActionPerformed

    private void txtDescriptionCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionCategoryActionPerformed
    }//GEN-LAST:event_txtDescriptionCategoryActionPerformed

    private void btnRegisterCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterCategoryActionPerformed
        String name = txtNameCategory.getText().trim();
        String description = txtDescriptionCategory.getText().trim();

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O nome da categoria é obrigatório!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            CategoryRequest request = new CategoryRequest();
            request.setName(name);
            request.setDescription(description.isEmpty() ? null : description);

            if (categoryResponse == null) {
                categoryController.create(request);
                JOptionPane.showMessageDialog(this, "Categoria criada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            } else {
                categoryController.update(categoryResponse.getId(), request);
                JOptionPane.showMessageDialog(this, "Categoria atualizada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                categoryResponse = null;
                btnRegisterCategory.setText("Criar");
            }

            refreshAllTables();
            setCategoryComboBox(categoryBox);
            switchScreens("Categories", SwitchPanels);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar categoria: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            logger.severe("Erro ao salvar categoria: " + e.getMessage());
        }
    }//GEN-LAST:event_btnRegisterCategoryActionPerformed

    // ------------------------------------------ PomodoroSession Screen -------------------------------------------- //
    private void btnReturnSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnSessionActionPerformed
        switchScreens("Initial", SwitchPanels);
    }//GEN-LAST:event_btnReturnSessionActionPerformed

    private void btnExitSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitSessionActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitSessionActionPerformed

    // -------------------------------------------------- Timer Methods --------------------------------------------- //
    private void updateTimerDisplay() {
        int remainingSeconds = totalSeconds - elapsedSeconds;
        int minutes = remainingSeconds / 60;
        int seconds = remainingSeconds % 60;
        lblTimer.setText(String.format("%02d:%02d", Integer.valueOf(minutes), Integer.valueOf(seconds)));
    }

    private void finishPomodoro() {
        if (pomodoroTimer != null) {
            pomodoroTimer.stop();
            pomodoroTimer = null;
        }

        TaskResponse selectedTask = (TaskResponse) boxTasks.getSelectedItem();
        String taskName = selectedTask != null ? selectedTask.getTitle() : "Tarefa";

        // Salvar sessão Pomodoro no banco de dados
        if (selectedTask != null && sessionStartTime != null) {
            try {
                PomodoroSessionRequest sessionRequest = new PomodoroSessionRequest();
                sessionRequest.setTarefaId(selectedTask.getId());
                sessionRequest.setDuration(Long.valueOf(totalSeconds)); // Duração em segundos
                sessionRequest.setCreatedAt(sessionStartTime);

                pomodoroSessionController.create(sessionRequest);

                // Atualizar a tabela de sessões
                loadSessionPomodoro();

                logger.info("Sessão Pomodoro salva com sucesso para a tarefa: " + taskName);
            } catch (Exception e) {
                logger.severe("Erro ao salvar sessão Pomodoro: " + e.getMessage());
                JOptionPane.showMessageDialog(this,
                        "Erro ao salvar a sessão Pomodoro: " + e.getMessage(),
                        "Erro",
                        JOptionPane.ERROR_MESSAGE);
            }
        }

        JOptionPane.showMessageDialog(this,
                "Parabéns! Você completou o Pomodoro da tarefa: " + taskName,
                "Pomodoro Concluído!",
                JOptionPane.INFORMATION_MESSAGE);

        // Resetar UI
        lblTimer.setText("00:00");
        lblTimer.setEnabled(false);
        progressDuration.setValue(0);
        txtStatus.setText("Status: Concluído");
        btnStartTask.setEnabled(true);
        btnPauseTask.setEnabled(false);
        btnStopTask.setEnabled(false);
        boxTasks.setEnabled(true);
        txtTaskDuration.setEnabled(true);

        // Resetar variáveis
        elapsedSeconds = 0;
        totalSeconds = 0;
        isPaused = false;
        sessionStartTime = null;
    }

    // --------------------------------------------------- Helpers -------------------------------------------------- //
    private void loadTasks() {
        List<TaskResponse> lista = taskController.findAll();
        taskTableModel = new TaskTableModel(lista);
        taskTable.setModel(taskTableModel);
    }

    private void loadCategories() {
        List<CategoryResponse> lista = categoryController.findAll();
        categoryTableModel = new CategoryTableModel(lista);
        categoryTable.setModel(categoryTableModel);
    }

    private void loadSessionPomodoro() {
        List<PomodoroSessionResponse> lista = pomodoroSessionController.findAll();
        pomodoroSessionTableModel = new PomodoroSessionTableModel(lista);
        sessionTable.setModel(pomodoroSessionTableModel);
    }

    private void refreshAllTables() {
        loadTasks();
        loadCategories();
        loadSessionPomodoro();
    }

    private void setCategoryComboBox(JComboBox<CategoryResponse> comboBox) {
        comboBox.removeAllItems();
        List<CategoryResponse> categories = categoryController.findAll();
        for (CategoryResponse cat : categories) {
            comboBox.addItem(cat);
        }

        comboBox.setRenderer(new DefaultListCellRenderer() {
                                 @Override
                                 public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                                     super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                                     if (value instanceof CategoryResponse) {
                                         setText(((CategoryResponse) value).getName());
                                     }
                                     return this;
                                 }
                             }
        );
    }

    private void setTaskComboBox(JComboBox<TaskResponse> comboBox) {
        comboBox.removeAllItems();
        List<TaskResponse> tasks = taskController.findAll();
        for (TaskResponse task : tasks) {
            comboBox.addItem(task);
        }

        comboBox.setRenderer(new DefaultListCellRenderer() {
                                 @Override
                                 public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                                     super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                                     if (value instanceof TaskResponse) {
                                         setText(((TaskResponse) value).getTitle());
                                     }
                                     return this;
                                 }
                             }
        );
    }

    private void switchScreens(String currentScreen, JTabbedPane jTabbedPane) {
        switch (currentScreen) {
            case "Initial":
                jTabbedPane.setSelectedIndex(0);
                break;
            case "Program":
                jTabbedPane.setSelectedIndex(1);
                break;
            case "Tasks":
                jTabbedPane.setSelectedIndex(2);
                break;
            case "Categories":
                jTabbedPane.setSelectedIndex(3);
                break;
            case "Sessions":
                jTabbedPane.setSelectedIndex(4);
                break;
            case "TaskRegister":
                jTabbedPane.setSelectedIndex(5);
                break;
            case "CategoryRegister":
                jTabbedPane.setSelectedIndex(6);
                break;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CategoryScreen;
    private javax.swing.JPanel CrudButtons;
    private javax.swing.JPanel InitialScreen;
    private javax.swing.JPanel Logo;
    private javax.swing.JPanel SessionScreen;
    private javax.swing.JPanel StartProgram;
    private javax.swing.JTabbedPane SwitchPanels;
    private javax.swing.JPanel TaskScreen;
    private javax.swing.JComboBox<TaskResponse> boxTasks;
    private javax.swing.JButton btnCreateCategory;
    private javax.swing.JButton btnCreateTask;
    private javax.swing.JButton btnCrudCategories;
    private javax.swing.JButton btnCrudSessions;
    private javax.swing.JButton btnCrudTasks;
    private javax.swing.JButton btnDeleteCategory;
    private javax.swing.JButton btnDeleteTask;
    private javax.swing.JButton btnExitCategory;
    private javax.swing.JButton btnExitProgram;
    private javax.swing.JButton btnExitSession;
    private javax.swing.JButton btnExitTask;
    private javax.swing.JButton btnPauseTask;
    private javax.swing.JButton btnRegisterCategory;
    private javax.swing.JButton btnRegisterTask;
    private javax.swing.JButton btnReturnCategory;
    private javax.swing.JButton btnReturnInitialTask;
    private javax.swing.JButton btnReturnSession;
    private javax.swing.JButton btnReturnTask;
    private javax.swing.JButton btnStartProgram;
    private javax.swing.JButton btnStartTask;
    private javax.swing.JButton btnStopTask;
    private javax.swing.JButton btnUpdateCategory;
    private javax.swing.JButton btnUpdateTask;
    private javax.swing.JComboBox<CategoryResponse> categoryBox;
    private javax.swing.JPanel categoryContent;
    private javax.swing.JPanel categoryOptions;
    private javax.swing.JPanel categoryRegisterPanel;
    private javax.swing.JPanel categoryRegisterScreen;
    private javax.swing.JScrollPane categoryScrollPane;
    private javax.swing.JTable categoryTable;
    private javax.swing.JPanel content;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblDescriptionCategory;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblNameCategory;
    private javax.swing.JLabel lblProgram;
    private javax.swing.JLabel lblTask;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JProgressBar progressDuration;
    private javax.swing.JPanel sessionContent;
    private javax.swing.JPanel sessionOptions;
    private javax.swing.JScrollPane sessionScrollPane;
    private javax.swing.JTable sessionTable;
    private javax.swing.JPanel taskContent;
    private javax.swing.JPanel taskOptions;
    private javax.swing.JPanel taskRegisterPanel;
    private javax.swing.JPanel taskRegisterScreen;
    private javax.swing.JScrollPane taskScrollPane;
    private javax.swing.JTable taskTable;
    private javax.swing.JTextField txtDescriptionCategory;
    private javax.swing.JTextField txtDescriptionTask;
    private javax.swing.JTextField txtNameCategory;
    private javax.swing.JLabel txtStatus;
    private javax.swing.JTextField txtTaskDuration;
    private javax.swing.JTextField txtTitleTask;
    // End of variables declaration//GEN-END:variables
}
