/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.view;

import br.com.controller.CategoryController;
import br.com.controller.TaskController;
import br.com.controller.PomodoroSessionController;
import br.com.dto.categoria.CategoryResponse;
import br.com.dto.tarefa.TaskResponse;
import br.com.dto.pomodoroSession.PomodoroSessionResponse;
import br.com.table.CategoryTableModel;
import br.com.table.TaskTableModel;
import br.com.table.PomodoroSessionTableModel;

import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author gabrielnathan
 */
public class MainScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainScreen.class.getName());
    private final CategoryController categoryController;
    private final TaskController taskController;
    private final PomodoroSessionController pomodoroSessionController;
    private CategoryTableModel categoryTableModel;
    private TaskTableModel taskTableModel;
    private PomodoroSessionTableModel pomodoroSessionTableModel;
    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        setLocationRelativeTo(null);
        this.categoryController = new CategoryController();
        this.taskController = new TaskController();
        this.pomodoroSessionController = new PomodoroSessionController();
        loadTasks();
        loadCategories();
        loadSessionPomodoro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SwitchPanels = new javax.swing.JTabbedPane();
        InitialScreen = new javax.swing.JPanel();
        Logo = new javax.swing.JPanel();
        lblProgram = new javax.swing.JLabel();
        CrudButtons = new javax.swing.JPanel();
        btnCrudTasks = new javax.swing.JButton();
        btnCrudCategories = new javax.swing.JButton();
        btnCrudSessions = new javax.swing.JButton();
        btnStartProgram = new javax.swing.JButton();
        StartProgram = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        lblTask = new javax.swing.JLabel();
        boxTasks = new javax.swing.JComboBox<>();
        btnStartTask = new javax.swing.JButton();
        lblDuration = new javax.swing.JLabel();
        txtTaskDuration = new javax.swing.JTextField();
        lblTimer = new javax.swing.JLabel();
        progressDuration = new javax.swing.JProgressBar();
        txtStatus = new javax.swing.JLabel();
        btnPauseTask = new javax.swing.JButton();
        btnExitProgram = new javax.swing.JButton();
        btnStopTask = new javax.swing.JButton();
        btnReturnInitialTask = new javax.swing.JButton();
        TaskScreen = new javax.swing.JPanel();
        taskOptions = new javax.swing.JPanel();
        btnCreateTask = new javax.swing.JButton();
        btnUpdateTask = new javax.swing.JButton();
        btnDeleteTask = new javax.swing.JButton();
        btnExitTask = new javax.swing.JButton();
        btnReturnTask = new javax.swing.JButton();
        taskContent = new javax.swing.JPanel();
        taskScrollPane = new javax.swing.JScrollPane();
        taskTable = new javax.swing.JTable();
        CategoryScreen = new javax.swing.JPanel();
        categoryOptions = new javax.swing.JPanel();
        btnCreateCategory = new javax.swing.JButton();
        btnUpdateCategory = new javax.swing.JButton();
        btnDeleteCategory = new javax.swing.JButton();
        btnExitCategory = new javax.swing.JButton();
        btnReturnCategory = new javax.swing.JButton();
        categoryContent = new javax.swing.JPanel();
        categoryScrollPane = new javax.swing.JScrollPane();
        categoryTable = new javax.swing.JTable();
        SessionScreen = new javax.swing.JPanel();
        sessionOptions = new javax.swing.JPanel();
        btnCreateSession = new javax.swing.JButton();
        btnUpdateSession = new javax.swing.JButton();
        btnDeleteSession = new javax.swing.JButton();
        btnExitSession = new javax.swing.JButton();
        btnReturnSession = new javax.swing.JButton();
        sessionContent = new javax.swing.JPanel();
        sessionScrollPane = new javax.swing.JScrollPane();
        sessionTable = new javax.swing.JTable();
        taskRegisterScreen = new javax.swing.JPanel();
        taskRegisterPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        categoryRegisterScreen = new javax.swing.JPanel();
        categoryRegisterPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        sessionRegisterScreen = new javax.swing.JPanel();
        sessionRegisterPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setName("MainFrame"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SwitchPanels.setMaximumSize(new java.awt.Dimension(800, 400));
        SwitchPanels.setMinimumSize(new java.awt.Dimension(800, 400));
        SwitchPanels.setPreferredSize(new java.awt.Dimension(800, 400));

        InitialScreen.setPreferredSize(new java.awt.Dimension(600, 400));

        Logo.setPreferredSize(new java.awt.Dimension(600, 150));

        lblProgram.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblProgram.setText("Pomodoro");
        lblProgram.setAlignmentY(0.0F);

        javax.swing.GroupLayout LogoLayout = new javax.swing.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(lblProgram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(255, 255, 255))
        );
        LogoLayout.setVerticalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(lblProgram)
                .addGap(44, 44, 44))
        );

        CrudButtons.setPreferredSize(new java.awt.Dimension(600, 250));

        btnCrudTasks.setText("Tarefas");
        btnCrudTasks.setMaximumSize(new java.awt.Dimension(50, 50));
        btnCrudTasks.setMinimumSize(new java.awt.Dimension(50, 50));
        btnCrudTasks.setPreferredSize(new java.awt.Dimension(25, 25));
        btnCrudTasks.addActionListener(this::btnCrudTasksActionPerformed);

        btnCrudCategories.setText("Categorias");
        btnCrudCategories.setMaximumSize(new java.awt.Dimension(50, 50));
        btnCrudCategories.setMinimumSize(new java.awt.Dimension(50, 50));
        btnCrudCategories.addActionListener(this::btnCrudCategoriesActionPerformed);

        btnCrudSessions.setText("Sessões");
        btnCrudSessions.addActionListener(this::btnCrudSessionsActionPerformed);

        btnStartProgram.setText("Iniciar Sessão");
        btnStartProgram.addActionListener(this::btnStartProgramActionPerformed);

        javax.swing.GroupLayout CrudButtonsLayout = new javax.swing.GroupLayout(CrudButtons);
        CrudButtons.setLayout(CrudButtonsLayout);
        CrudButtonsLayout.setHorizontalGroup(
            CrudButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrudButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CrudButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnCrudSessions, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrudCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrudTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStartProgram))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CrudButtonsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCrudCategories, btnCrudSessions, btnCrudTasks, btnStartProgram});

        CrudButtonsLayout.setVerticalGroup(
            CrudButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrudButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStartProgram)
                .addGap(9, 9, 9)
                .addComponent(btnCrudTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCrudCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCrudSessions, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout InitialScreenLayout = new javax.swing.GroupLayout(InitialScreen);
        InitialScreen.setLayout(InitialScreenLayout);
        InitialScreenLayout.setHorizontalGroup(
            InitialScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InitialScreenLayout.createSequentialGroup()
                .addGroup(InitialScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CrudButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        InitialScreenLayout.setVerticalGroup(
            InitialScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InitialScreenLayout.createSequentialGroup()
                .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CrudButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        SwitchPanels.addTab("tab4", InitialScreen);

        StartProgram.setMaximumSize(new java.awt.Dimension(600, 400));
        StartProgram.setMinimumSize(new java.awt.Dimension(600, 400));
        StartProgram.setPreferredSize(new java.awt.Dimension(600, 400));

        content.setAlignmentX(0.0F);
        content.setAlignmentY(0.0F);
        content.setMaximumSize(new java.awt.Dimension(600, 400));
        content.setMinimumSize(new java.awt.Dimension(600, 150));

        lblTask.setText("Tarefas");

        boxTasks.addActionListener(this::boxTasksActionPerformed);

        btnStartTask.setText("Iniciar");
        btnStartTask.addActionListener(this::btnStartTaskActionPerformed);

        lblDuration.setText("Duração (min):");

        txtTaskDuration.addActionListener(this::txtTaskDurationActionPerformed);

        lblTimer.setFont(new java.awt.Font("JetBrainsMono NF", 1, 24)); // NOI18N
        lblTimer.setText("00:00");
        lblTimer.setEnabled(false);
        lblTimer.setPreferredSize(new java.awt.Dimension(148, 33));

        progressDuration.setBackground(new java.awt.Color(255, 255, 255));
        progressDuration.setToolTipText("0");
        progressDuration.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        progressDuration.setEnabled(false);
        progressDuration.setStringPainted(true);

        txtStatus.setText("Status: -");
        txtStatus.setEnabled(false);
        txtStatus.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        txtStatus.setMaximumSize(new java.awt.Dimension(148, 15));
        txtStatus.setMinimumSize(new java.awt.Dimension(148, 15));
        txtStatus.setPreferredSize(new java.awt.Dimension(148, 15));

        btnPauseTask.setText("Pausar");
        btnPauseTask.setEnabled(false);
        btnPauseTask.addActionListener(this::btnPauseTaskActionPerformed);

        btnExitProgram.setText("Sair");
        btnExitProgram.addActionListener(this::btnExitProgramActionPerformed);

        btnStopTask.setText("Parar");
        btnStopTask.setEnabled(false);
        btnStopTask.addActionListener(this::btnStopTaskActionPerformed);

        btnReturnInitialTask.setText("Voltar");
        btnReturnInitialTask.addActionListener(this::btnReturnInitialTaskActionPerformed);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(progressDuration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTask)
                                    .addComponent(lblDuration))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boxTasks, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTaskDuration)))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addComponent(btnReturnInitialTask, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExitProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnStartTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPauseTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStopTask, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnReturnInitialTask, lblDuration, lblTask});

        contentLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {boxTasks, btnExitProgram, txtTaskDuration});

        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(lblTimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxTasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTask)
                    .addComponent(btnStartTask))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTaskDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDuration)
                    .addComponent(btnPauseTask))
                .addGap(0, 37, Short.MAX_VALUE)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturnInitialTask)
                    .addComponent(btnExitProgram)
                    .addComponent(btnStopTask))
                .addGap(120, 120, 120))
        );

        btnStartTask.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout StartProgramLayout = new javax.swing.GroupLayout(StartProgram);
        StartProgram.setLayout(StartProgramLayout);
        StartProgramLayout.setHorizontalGroup(
            StartProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartProgramLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StartProgramLayout.setVerticalGroup(
            StartProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartProgramLayout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SwitchPanels.addTab("tab1", StartProgram);

        TaskScreen.setMaximumSize(new java.awt.Dimension(600, 400));
        TaskScreen.setMinimumSize(new java.awt.Dimension(600, 400));
        TaskScreen.setPreferredSize(new java.awt.Dimension(600, 400));

        taskOptions.setMaximumSize(new java.awt.Dimension(600, 100));
        taskOptions.setMinimumSize(new java.awt.Dimension(600, 100));

        btnCreateTask.setText("Criar");
        btnCreateTask.addActionListener(this::btnCreateTaskActionPerformed);

        btnUpdateTask.setText("Atualizar");
        btnUpdateTask.addActionListener(this::btnUpdateTaskActionPerformed);

        btnDeleteTask.setText("Excluir");
        btnDeleteTask.addActionListener(this::btnDeleteTaskActionPerformed);

        btnExitTask.setText("Sair");
        btnExitTask.addActionListener(this::btnExitTaskActionPerformed);

        btnReturnTask.setText("Voltar");
        btnReturnTask.addActionListener(this::btnReturnTaskActionPerformed);

        javax.swing.GroupLayout taskOptionsLayout = new javax.swing.GroupLayout(taskOptions);
        taskOptions.setLayout(taskOptionsLayout);
        taskOptionsLayout.setHorizontalGroup(
            taskOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(taskOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(taskOptionsLayout.createSequentialGroup()
                        .addComponent(btnReturnTask, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExitTask, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(taskOptionsLayout.createSequentialGroup()
                        .addComponent(btnCreateTask, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateTask, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteTask, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(342, Short.MAX_VALUE))
        );
        taskOptionsLayout.setVerticalGroup(
            taskOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taskOptionsLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(taskOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturnTask)
                    .addComponent(btnExitTask))
                .addGap(18, 18, 18)
                .addGroup(taskOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateTask)
                    .addComponent(btnDeleteTask)
                    .addComponent(btnCreateTask))
                .addContainerGap())
        );

        taskContent.setAlignmentX(0.0F);
        taskContent.setAlignmentY(0.0F);
        taskContent.setMaximumSize(new java.awt.Dimension(600, 300));
        taskContent.setMinimumSize(new java.awt.Dimension(600, 300));

        taskScrollPane.setAlignmentX(0.0F);
        taskScrollPane.setAlignmentY(0.0F);
        taskScrollPane.setMaximumSize(new java.awt.Dimension(600, 300));
        taskScrollPane.setMinimumSize(new java.awt.Dimension(600, 300));
        taskScrollPane.setPreferredSize(new java.awt.Dimension(600, 300));

        taskTable.setAlignmentX(0.0F);
        taskTable.setAlignmentY(0.0F);
        taskTable.setMaximumSize(new java.awt.Dimension(600, 80));
        taskTable.setMinimumSize(new java.awt.Dimension(600, 80));
        taskTable.setPreferredSize(new java.awt.Dimension(600, 300));
        taskScrollPane.setViewportView(taskTable);

        javax.swing.GroupLayout taskContentLayout = new javax.swing.GroupLayout(taskContent);
        taskContent.setLayout(taskContentLayout);
        taskContentLayout.setHorizontalGroup(
            taskContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taskScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        taskContentLayout.setVerticalGroup(
            taskContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskContentLayout.createSequentialGroup()
                .addComponent(taskScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout TaskScreenLayout = new javax.swing.GroupLayout(TaskScreen);
        TaskScreen.setLayout(TaskScreenLayout);
        TaskScreenLayout.setHorizontalGroup(
            TaskScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaskScreenLayout.createSequentialGroup()
                .addGroup(TaskScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taskOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taskContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
        TaskScreenLayout.setVerticalGroup(
            TaskScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaskScreenLayout.createSequentialGroup()
                .addComponent(taskOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(taskContent, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        SwitchPanels.addTab("tab2", TaskScreen);

        CategoryScreen.setMaximumSize(new java.awt.Dimension(600, 400));
        CategoryScreen.setMinimumSize(new java.awt.Dimension(600, 400));

        categoryOptions.setMaximumSize(new java.awt.Dimension(600, 100));
        categoryOptions.setMinimumSize(new java.awt.Dimension(600, 100));

        btnCreateCategory.setText("Criar");
        btnCreateCategory.addActionListener(this::btnCreateCategoryActionPerformed);

        btnUpdateCategory.setText("Atualizar");
        btnUpdateCategory.addActionListener(this::btnUpdateCategoryActionPerformed);

        btnDeleteCategory.setText("Excluir");
        btnDeleteCategory.addActionListener(this::btnDeleteCategoryActionPerformed);

        btnExitCategory.setText("Sair");
        btnExitCategory.addActionListener(this::btnExitCategoryActionPerformed);

        btnReturnCategory.setText("Voltar");
        btnReturnCategory.addActionListener(this::btnReturnCategoryActionPerformed);

        javax.swing.GroupLayout categoryOptionsLayout = new javax.swing.GroupLayout(categoryOptions);
        categoryOptions.setLayout(categoryOptionsLayout);
        categoryOptionsLayout.setHorizontalGroup(
            categoryOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoryOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(categoryOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(categoryOptionsLayout.createSequentialGroup()
                        .addComponent(btnReturnCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExitCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(categoryOptionsLayout.createSequentialGroup()
                        .addComponent(btnCreateCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(342, Short.MAX_VALUE))
        );
        categoryOptionsLayout.setVerticalGroup(
            categoryOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, categoryOptionsLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(categoryOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturnCategory)
                    .addComponent(btnExitCategory))
                .addGap(18, 18, 18)
                .addGroup(categoryOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateCategory)
                    .addComponent(btnDeleteCategory)
                    .addComponent(btnCreateCategory))
                .addGap(12, 12, 12))
        );

        categoryContent.setAlignmentX(0.0F);
        categoryContent.setAlignmentY(0.0F);
        categoryContent.setMaximumSize(new java.awt.Dimension(600, 300));
        categoryContent.setMinimumSize(new java.awt.Dimension(600, 300));

        categoryScrollPane.setAlignmentX(0.0F);
        categoryScrollPane.setAlignmentY(0.0F);
        categoryScrollPane.setMaximumSize(new java.awt.Dimension(600, 300));
        categoryScrollPane.setMinimumSize(new java.awt.Dimension(600, 300));
        categoryScrollPane.setPreferredSize(new java.awt.Dimension(600, 300));

        categoryTable.setAlignmentX(0.0F);
        categoryTable.setAlignmentY(0.0F);
        categoryTable.setMaximumSize(new java.awt.Dimension(600, 80));
        categoryTable.setMinimumSize(new java.awt.Dimension(600, 80));
        categoryTable.setPreferredSize(new java.awt.Dimension(600, 300));
        categoryScrollPane.setViewportView(categoryTable);

        javax.swing.GroupLayout categoryContentLayout = new javax.swing.GroupLayout(categoryContent);
        categoryContent.setLayout(categoryContentLayout);
        categoryContentLayout.setHorizontalGroup(
            categoryContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoryContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(categoryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 588, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        categoryContentLayout.setVerticalGroup(
            categoryContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoryContentLayout.createSequentialGroup()
                .addComponent(categoryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CategoryScreenLayout = new javax.swing.GroupLayout(CategoryScreen);
        CategoryScreen.setLayout(CategoryScreenLayout);
        CategoryScreenLayout.setHorizontalGroup(
            CategoryScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoryScreenLayout.createSequentialGroup()
                .addGroup(CategoryScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categoryOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
        CategoryScreenLayout.setVerticalGroup(
            CategoryScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoryScreenLayout.createSequentialGroup()
                .addComponent(categoryOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(categoryContent, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        SwitchPanels.addTab("tab2", CategoryScreen);

        SessionScreen.setPreferredSize(new java.awt.Dimension(600, 400));

        sessionOptions.setMaximumSize(new java.awt.Dimension(600, 100));
        sessionOptions.setMinimumSize(new java.awt.Dimension(600, 100));
        sessionOptions.setPreferredSize(new java.awt.Dimension(600, 100));

        btnCreateSession.setText("Criar");
        btnCreateSession.addActionListener(this::btnCreateSessionActionPerformed);

        btnUpdateSession.setText("Atualizar");
        btnUpdateSession.addActionListener(this::btnUpdateSessionActionPerformed);

        btnDeleteSession.setText("Excluir");
        btnDeleteSession.addActionListener(this::btnDeleteSessionActionPerformed);

        btnExitSession.setText("Sair");
        btnExitSession.addActionListener(this::btnExitSessionActionPerformed);

        btnReturnSession.setText("Voltar");
        btnReturnSession.addActionListener(this::btnReturnSessionActionPerformed);

        javax.swing.GroupLayout sessionOptionsLayout = new javax.swing.GroupLayout(sessionOptions);
        sessionOptions.setLayout(sessionOptionsLayout);
        sessionOptionsLayout.setHorizontalGroup(
            sessionOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sessionOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sessionOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sessionOptionsLayout.createSequentialGroup()
                        .addComponent(btnReturnSession, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExitSession, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sessionOptionsLayout.createSequentialGroup()
                        .addComponent(btnCreateSession, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateSession, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteSession, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(342, Short.MAX_VALUE))
        );
        sessionOptionsLayout.setVerticalGroup(
            sessionOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sessionOptionsLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(sessionOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturnSession)
                    .addComponent(btnExitSession))
                .addGap(18, 18, 18)
                .addGroup(sessionOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateSession)
                    .addComponent(btnDeleteSession)
                    .addComponent(btnCreateSession))
                .addContainerGap())
        );

        sessionContent.setAlignmentX(0.0F);
        sessionContent.setAlignmentY(0.0F);
        sessionContent.setMaximumSize(new java.awt.Dimension(600, 300));
        sessionContent.setMinimumSize(new java.awt.Dimension(600, 300));
        sessionContent.setPreferredSize(new java.awt.Dimension(600, 300));

        sessionScrollPane.setAlignmentX(0.0F);
        sessionScrollPane.setAlignmentY(0.0F);
        sessionScrollPane.setMaximumSize(new java.awt.Dimension(600, 300));
        sessionScrollPane.setMinimumSize(new java.awt.Dimension(600, 300));
        sessionScrollPane.setPreferredSize(new java.awt.Dimension(600, 300));

        sessionTable.setAlignmentX(0.0F);
        sessionTable.setAlignmentY(0.0F);
        sessionTable.setMaximumSize(new java.awt.Dimension(600, 80));
        sessionTable.setMinimumSize(new java.awt.Dimension(600, 80));
        sessionTable.setPreferredSize(new java.awt.Dimension(600, 300));
        sessionScrollPane.setViewportView(sessionTable);

        javax.swing.GroupLayout sessionContentLayout = new javax.swing.GroupLayout(sessionContent);
        sessionContent.setLayout(sessionContentLayout);
        sessionContentLayout.setHorizontalGroup(
            sessionContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sessionContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sessionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        sessionContentLayout.setVerticalGroup(
            sessionContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sessionContentLayout.createSequentialGroup()
                .addComponent(sessionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout SessionScreenLayout = new javax.swing.GroupLayout(SessionScreen);
        SessionScreen.setLayout(SessionScreenLayout);
        SessionScreenLayout.setHorizontalGroup(
            SessionScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SessionScreenLayout.createSequentialGroup()
                .addGroup(SessionScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sessionOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sessionContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
        SessionScreenLayout.setVerticalGroup(
            SessionScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SessionScreenLayout.createSequentialGroup()
                .addComponent(sessionOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sessionContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        SwitchPanels.addTab("tab2", SessionScreen);

        taskRegisterScreen.setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel1.setText("Título");

        jLabel2.setText("Descrição");

        jLabel4.setText("Categoria");

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        jTextField3.addActionListener(this::jTextField3ActionPerformed);

        jButton1.setText("Criar");
        jButton1.setPreferredSize(new java.awt.Dimension(64, 22));
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout taskRegisterPanelLayout = new javax.swing.GroupLayout(taskRegisterPanel);
        taskRegisterPanel.setLayout(taskRegisterPanelLayout);
        taskRegisterPanelLayout.setHorizontalGroup(
            taskRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskRegisterPanelLayout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addGroup(taskRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3)
                    .addComponent(jTextField2)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 266, Short.MAX_VALUE))
        );

        taskRegisterPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jLabel1, jLabel2, jLabel4, jTextField1, jTextField2, jTextField3});

        taskRegisterPanelLayout.setVerticalGroup(
            taskRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskRegisterPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );

        javax.swing.GroupLayout taskRegisterScreenLayout = new javax.swing.GroupLayout(taskRegisterScreen);
        taskRegisterScreen.setLayout(taskRegisterScreenLayout);
        taskRegisterScreenLayout.setHorizontalGroup(
            taskRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskRegisterScreenLayout.createSequentialGroup()
                .addComponent(taskRegisterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        taskRegisterScreenLayout.setVerticalGroup(
            taskRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taskRegisterScreenLayout.createSequentialGroup()
                .addComponent(taskRegisterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        SwitchPanels.addTab("tab5", taskRegisterScreen);

        jLabel3.setText("Nome");

        jLabel5.setText("Descrição");

        jTextField4.addActionListener(this::jTextField4ActionPerformed);

        jTextField5.addActionListener(this::jTextField5ActionPerformed);

        jButton2.setText("Criar");
        jButton2.setPreferredSize(new java.awt.Dimension(64, 22));
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout categoryRegisterPanelLayout = new javax.swing.GroupLayout(categoryRegisterPanel);
        categoryRegisterPanel.setLayout(categoryRegisterPanelLayout);
        categoryRegisterPanelLayout.setHorizontalGroup(
            categoryRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoryRegisterPanelLayout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addGroup(categoryRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 266, Short.MAX_VALUE))
        );

        categoryRegisterPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField4, jTextField5});

        categoryRegisterPanelLayout.setVerticalGroup(
            categoryRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoryRegisterPanelLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );

        javax.swing.GroupLayout categoryRegisterScreenLayout = new javax.swing.GroupLayout(categoryRegisterScreen);
        categoryRegisterScreen.setLayout(categoryRegisterScreenLayout);
        categoryRegisterScreenLayout.setHorizontalGroup(
            categoryRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoryRegisterScreenLayout.createSequentialGroup()
                .addComponent(categoryRegisterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        categoryRegisterScreenLayout.setVerticalGroup(
            categoryRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, categoryRegisterScreenLayout.createSequentialGroup()
                .addComponent(categoryRegisterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        SwitchPanels.addTab("tab5", categoryRegisterScreen);

        jLabel7.setText("Título");

        jLabel8.setText("Descrição");

        jLabel9.setText("Categoria");

        jTextField7.addActionListener(this::jTextField7ActionPerformed);

        jTextField8.addActionListener(this::jTextField8ActionPerformed);

        jTextField9.addActionListener(this::jTextField9ActionPerformed);

        jButton3.setText("Criar");
        jButton3.setPreferredSize(new java.awt.Dimension(64, 22));
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout sessionRegisterPanelLayout = new javax.swing.GroupLayout(sessionRegisterPanel);
        sessionRegisterPanel.setLayout(sessionRegisterPanelLayout);
        sessionRegisterPanelLayout.setHorizontalGroup(
            sessionRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sessionRegisterPanelLayout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addGroup(sessionRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 266, Short.MAX_VALUE))
        );

        sessionRegisterPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField7, jTextField8});

        sessionRegisterPanelLayout.setVerticalGroup(
            sessionRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sessionRegisterPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );

        javax.swing.GroupLayout sessionRegisterScreenLayout = new javax.swing.GroupLayout(sessionRegisterScreen);
        sessionRegisterScreen.setLayout(sessionRegisterScreenLayout);
        sessionRegisterScreenLayout.setHorizontalGroup(
            sessionRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sessionRegisterScreenLayout.createSequentialGroup()
                .addComponent(sessionRegisterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        sessionRegisterScreenLayout.setVerticalGroup(
            sessionRegisterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sessionRegisterScreenLayout.createSequentialGroup()
                .addComponent(sessionRegisterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        SwitchPanels.addTab("tab5", sessionRegisterScreen);

        getContentPane().add(SwitchPanels, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -36, 600, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Initial Screen
    private void btnCrudTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrudTasksActionPerformed
        // TODO add your handling code here:
        switchScreens("Tasks", SwitchPanels);
    }//GEN-LAST:event_btnCrudTasksActionPerformed

    private void btnCrudSessionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrudSessionsActionPerformed
        // TODO add your handling code here:
        switchScreens("Sessions", SwitchPanels);
    }//GEN-LAST:event_btnCrudSessionsActionPerformed

    private void btnCrudCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrudCategoriesActionPerformed
        // TODO add your handling code here:
        switchScreens("Categories", SwitchPanels);
    }//GEN-LAST:event_btnCrudCategoriesActionPerformed
    
    // Task Screen
    private void btnStartTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStartTaskActionPerformed

    private void txtTaskDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaskDurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTaskDurationActionPerformed

    private void boxTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTasksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxTasksActionPerformed

    private void btnPauseTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseTaskActionPerformed
        // TODO add your handling code here:
        switchScreens("Initial", SwitchPanels);
    }//GEN-LAST:event_btnPauseTaskActionPerformed

    private void btnExitProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitProgramActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitProgramActionPerformed

    private void btnStopTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStopTaskActionPerformed

    private void btnReturnInitialTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnInitialTaskActionPerformed
        // TODO add your handling code here:
        switchScreens("Initial", SwitchPanels);
    }//GEN-LAST:event_btnReturnInitialTaskActionPerformed

    private void loadTasks() {
        List<TaskResponse> lista = taskController.findAll();
        taskTableModel = new TaskTableModel(lista);
        taskTable.setModel(taskTableModel);
    }
    
    private void loadCategories() {
        List<CategoryResponse> lista = categoryController.findAll();
        categoryTableModel = new CategoryTableModel(lista);
        categoryTable.setModel(categoryTableModel);
    }
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnStartProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartProgramActionPerformed
        // TODO add your handling code here:
        switchScreens("Program", SwitchPanels);
    }//GEN-LAST:event_btnStartProgramActionPerformed

    private void btnReturnSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnSessionActionPerformed
        // TODO add your handling code here:
        switchScreens("Initial", SwitchPanels);
    }//GEN-LAST:event_btnReturnSessionActionPerformed

    private void btnExitSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitSessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitSessionActionPerformed

    private void btnDeleteSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSessionActionPerformed
        // TODO add your handling code here:
        int row = sessionTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma categoria.");
            return;
        }

        Long id = (Long) sessionTable.getValueAt(row, 0);

        if (JOptionPane.showConfirmDialog(this, "Excluir categoria?") == 0) {
            categoryController.delete(id);
            loadCategories();
        }
    }//GEN-LAST:event_btnDeleteSessionActionPerformed

    private void btnUpdateSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateSessionActionPerformed

    // Category Screen
    private void btnCreateSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateSessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateSessionActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnCreateTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateTaskActionPerformed

    private void btnUpdateTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateTaskActionPerformed

    private void btnDeleteTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteTaskActionPerformed

    private void btnExitTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitTaskActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitTaskActionPerformed

    private void btnReturnTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnTaskActionPerformed
        // TODO add your handling code here:
        switchScreens("Initial", SwitchPanels);
    }//GEN-LAST:event_btnReturnTaskActionPerformed

    private void btnCreateCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateCategoryActionPerformed

    private void btnUpdateCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateCategoryActionPerformed

    private void btnDeleteCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteCategoryActionPerformed

    private void btnExitCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitCategoryActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitCategoryActionPerformed

    private void btnReturnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnCategoryActionPerformed
        // TODO add your handling code here:
        switchScreens("Initial", SwitchPanels);
    }//GEN-LAST:event_btnReturnCategoryActionPerformed

    private void loadSessionPomodoro() {
        List<PomodoroSessionResponse> lista = pomodoroSessionController.findAll();
        pomodoroSessionTableModel = new PomodoroSessionTableModel(lista);
        sessionTable.setModel(pomodoroSessionTableModel);
    }
    
    private void switchScreens(String currentScreen, JTabbedPane jTabbedPane) {
        switch(currentScreen) {
            case "Initial": jTabbedPane.setSelectedIndex(0);
                break;
            case "Program": jTabbedPane.setSelectedIndex(1);
                break;
            case "Tasks":
                jTabbedPane.setSelectedIndex(2);
                break;
            case "Categories":
                jTabbedPane.setSelectedIndex(3);
                break;
            case "Sessions":
                jTabbedPane.setSelectedIndex(4);
                break;
            case "TaskRegister":
                jTabbedPane.setSelectedIndex(5);
                break;
            case "CategoryRegister":
                jTabbedPane.setSelectedIndex(6);
                break;
            case "SessionRegister":
                jTabbedPane.setSelectedIndex(7);
                break;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CategoryScreen;
    private javax.swing.JPanel CrudButtons;
    private javax.swing.JPanel InitialScreen;
    private javax.swing.JPanel Logo;
    private javax.swing.JPanel SessionScreen;
    private javax.swing.JPanel StartProgram;
    private javax.swing.JTabbedPane SwitchPanels;
    private javax.swing.JPanel TaskScreen;
    private javax.swing.JComboBox<String> boxTasks;
    private javax.swing.JButton btnCreateCategory;
    private javax.swing.JButton btnCreateSession;
    private javax.swing.JButton btnCreateTask;
    private javax.swing.JButton btnCrudCategories;
    private javax.swing.JButton btnCrudSessions;
    private javax.swing.JButton btnCrudTasks;
    private javax.swing.JButton btnDeleteCategory;
    private javax.swing.JButton btnDeleteSession;
    private javax.swing.JButton btnDeleteTask;
    private javax.swing.JButton btnExitCategory;
    private javax.swing.JButton btnExitProgram;
    private javax.swing.JButton btnExitSession;
    private javax.swing.JButton btnExitTask;
    private javax.swing.JButton btnPauseTask;
    private javax.swing.JButton btnReturnCategory;
    private javax.swing.JButton btnReturnInitialTask;
    private javax.swing.JButton btnReturnSession;
    private javax.swing.JButton btnReturnTask;
    private javax.swing.JButton btnStartProgram;
    private javax.swing.JButton btnStartTask;
    private javax.swing.JButton btnStopTask;
    private javax.swing.JButton btnUpdateCategory;
    private javax.swing.JButton btnUpdateSession;
    private javax.swing.JButton btnUpdateTask;
    private javax.swing.JPanel categoryContent;
    private javax.swing.JPanel categoryOptions;
    private javax.swing.JPanel categoryRegisterPanel;
    private javax.swing.JPanel categoryRegisterScreen;
    private javax.swing.JScrollPane categoryScrollPane;
    private javax.swing.JTable categoryTable;
    private javax.swing.JPanel content;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblProgram;
    private javax.swing.JLabel lblTask;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JProgressBar progressDuration;
    private javax.swing.JPanel sessionContent;
    private javax.swing.JPanel sessionOptions;
    private javax.swing.JPanel sessionRegisterPanel;
    private javax.swing.JPanel sessionRegisterScreen;
    private javax.swing.JScrollPane sessionScrollPane;
    private javax.swing.JTable sessionTable;
    private javax.swing.JPanel taskContent;
    private javax.swing.JPanel taskOptions;
    private javax.swing.JPanel taskRegisterPanel;
    private javax.swing.JPanel taskRegisterScreen;
    private javax.swing.JScrollPane taskScrollPane;
    private javax.swing.JTable taskTable;
    private javax.swing.JLabel txtStatus;
    private javax.swing.JTextField txtTaskDuration;
    // End of variables declaration//GEN-END:variables
}
